android/compose-samples

JetNews/app/build.gradle

Disable vector drawable rasterization.

---

JetNews/app/build.gradle.kts
JetNews/build.gradle.kts

Updates Kotlin to latest EAP (1.3.60-eap-76) and bumps KTlint

---

JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsScreen.kt

use camelCase in a variable name

---

JetNews/app/build.gradle
JetNews/app/src/androidTest/java/com/example/jetnews/JetnewsUiTest.kt
JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsApp.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/PostContent.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/PostCardTop.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/PostCardYourNetwork.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/SelectTopicButton.kt
JetNews/build.gradle
JetNews/gradle/wrapper/gradle-wrapper.properties

Changes:
- Bumped version
- Convert screens to use new Scaffold component
- Use modifiers for PostCardPopular instead of Space for margin
- Add @Preview throughout for various states and components
- Fixed all warnings
- Updated to new Ambient syntax

Bump to dev05 snapshot version

---

JetNews/app/src/androidTest/java/com/example/jetnews/JetnewsUiTest.kt

This a merge commit pull latest master over to develop.
After this, develop -> master will be possible.

Dev05 rebase

---

README.md

Fixed readme links to sunflower and tivi

doc: Fixed readme links to sunflower and tivi

---

Jetcaster/app/build.gradle

CI should only build Jetcaster :crossed_fingers:

[Jetcaster] remove unnecessary deps

---

Owl/app/src/main/java/com/example/owl/ui/common/CourseListItem.kt
Owl/app/src/main/java/com/example/owl/ui/course/CourseDetails.kt
Owl/app/src/main/java/com/example/owl/ui/courses/Courses.kt
Owl/app/src/main/java/com/example/owl/ui/courses/SearchCourses.kt
Owl/app/src/main/java/com/example/owl/ui/onboarding/Onboarding.kt
Owl/app/src/main/java/com/example/owl/ui/utils/Insets.kt
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt
Owl/gradle/wrapper/gradle-wrapper.properties

Change-Id: Ia21b9245a8c040acd4ef8da0c16045e9317beef2

[Owl] Update to alpha03.

---

Jetcaster/app/src/main/java/com/example/jetcaster/data/OkHttpExtensions.kt
Jetcaster/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetcaster/gradle/wrapper/gradle-wrapper.properties

Also updated:
- AGP
- Gradle
- ktlint
- Spotless

[Jetcaster] Update to Compose 1.0.0-alpha02

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/Conversation.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/profile/Profile.kt

Replacing TODOs with FunctionalityNotAvailablePopup in Conversation and Profile AppBar.
Preview:

[Jetchat] Show not implemented popup

---

Crane/app/src/main/java/androidx/compose/samples/crane/calendar/Calendar.kt
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/NavActivity.kt
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Jetsurvey/gradle/wrapper/gradle-wrapper.properties
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt
Rally/buildSrc/src/main/java/com/example/compose/rally/buildsrc/dependencies.kt

Change-Id: Ibb9d24866949ff55ce2c0d66e7e9c99d44f472df

Update all samples to alpha03.

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInSignUp.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignUpScreen.kt

Updating Sign In and Sign Up screens to use `Scaffold`

[Jetsurvey] Using alpha03 Snackbar APIs

---

.github/workflows/Release.yml

This new action will trigger when we create a tag. I'll test this on `1.0.0-alpha03` once merged.

Automatically create GitHub release with APKs

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInSignUp.kt

* Sign up - password validation not showing
* Sign in - enabling the sign in button when email AND password are valid

[Jetsurvey] Password validation errors fixed

---

Jetchat/app/src/androidTest/java/com/example/compose/jetchat/UserInputTest.kt

[Jetchat] Works around keyboard test flakiness

[Jetchat] Works around keyboard test flakiness

---

Owl/app/build.gradle
Owl/app/src/main/java/com/example/owl/ui/MainActivity.kt
Owl/app/src/main/java/com/example/owl/ui/common/OutlinedAvatar.kt
Owl/app/src/main/java/com/example/owl/ui/course/CourseDetails.kt
Owl/app/src/main/java/com/example/owl/ui/onboarding/Onboarding.kt
Owl/app/src/main/res/values-night/themes.xml
Owl/build.gradle
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt

Change-Id: I32373189784f0ef805c2d697ad077111b6dfdcdf

[Owl] Update to snapshot 6860046.

---

Jetsnack/app/build.gradle
Jetsnack/app/src/main/java/com/example/jetsnack/ui/MainActivity.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/Button.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/Filters.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/Snacks.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/Surface.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/Feed.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/Home.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/search/Results.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/search/Search.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/snackdetail/SnackDetail.kt
Jetsnack/app/src/main/res/values-night/themes.xml
Jetsnack/build.gradle
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt

Change-Id: I90576abb41898e7cddbc5a619f87e28195be4741

[Jetsnack] Update to snapshot 6860046.

---

Crane/app/src/main/java/androidx/compose/samples/crane/calendar/data/CalendarData.kt

Hi,
I found small mistakes in CalendarData.kt, and fix them.

[Crane] Fix CalendarData.

---

Crane/app/src/main/java/androidx/compose/samples/crane/calendar/data/CalendarData.kt

My bad! Merged directly to `main`, merging `main` into `dev_alpha06`

[Crane] fix CalendarData (#240)

---

.github/ci-gradle.properties
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
Crane/gradle.properties
JetNews/build.gradle
JetNews/gradle.properties
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetcaster/gradle.properties
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetchat/gradle.properties
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsnack/gradle.properties
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/EmailState.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/PasswordState.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/UserRepository.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyFragment.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyRepository.kt
Jetsurvey/build.gradle
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Jetsurvey/gradle.properties
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt
Owl/gradle.properties
Rally/buildSrc/src/main/java/com/example/compose/rally/buildsrc/dependencies.kt
Rally/gradle.properties

See commits for more info (I won't squash this)

Just a few tidy-ups

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/Conversation.kt

Fixes text opacity in JetchatAppBar

---

.github/workflows/Crane.yaml
.github/workflows/JetNews.yaml
.github/workflows/Jetcaster.yaml
.github/workflows/Jetchat.yaml
.github/workflows/Jetsnack.yaml
.github/workflows/Jetsurvey.yaml
.github/workflows/Owl.yaml
.github/workflows/Rally.yaml
.github/workflows/Release.yml
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
Crane/gradle/wrapper/gradle-wrapper.properties
JetNews/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetchat/gradle/wrapper/gradle-wrapper.properties
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt
Rally/buildSrc/src/main/java/com/example/compose/rally/buildsrc/dependencies.kt
Rally/gradle/wrapper/gradle-wrapper.properties

Upgrade Android Gradle plugin to 7.0.0-alpha01
Upgrade Gradle to 6.7.1

[All] Updating to Compose alpha08

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/ConversationFragment.kt

[Jetchat] Fix regression from #388

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/Conversation.kt
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt

- Update to AndroidX Core 1.5.0-beta02: Fixes a crash on API 21 devices for WindowInsetsAnimations.
- Fix LazyColumn usage

[Jetchat] Small improvements

---

Crane/app/build.gradle
Crane/app/src/androidTest/java/androidx/compose/samples/crane/home/HomeTest.kt
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/app/build.gradle
JetNews/build.gradle
Jetcaster/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetchat/app/src/androidTest/java/com/example/compose/jetchat/ConversationTest.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/Conversation.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/UserInput.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/data/FakeData.kt
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/utils/SystemUi.kt
Jetsnack/build.gradle
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/build.gradle
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Owl/build.gradle
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt
Rally/buildSrc/src/main/java/com/example/compose/rally/buildsrc/dependencies.kt

[All] Update to beta02

---

JetNews/app/src/main/java/com/example/jetnews/utils/ProduceUiState.kt

Fix typo in comments in ProduceUiState.kt

[JetNews] Fix typo in comments in ProduceUiState.kt

---

Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt
Rally/buildSrc/src/main/java/com/example/compose/rally/buildsrc/dependencies.kt

Change-Id: I97dd9cb0e893769cf5d96f6cab1f74520d36dfc2

[All] Update to AGP 7.0.0-alpha11

---

Jetsnack/app/build.gradle
Jetsnack/app/src/androidTest/java/com/example/jetsnack/AppTest.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/Home.kt
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt

Adds simple navigation tests to Jetsnack.
Note: We don't have to worry about the animations in the bottom bar, the test framework takes care of that 👌

[Jetsnack] Add tests

---

Crane/app/src/main/java/androidx/compose/samples/crane/base/ExploreSection.kt
Crane/build.gradle
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt
Jetcaster/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/Snacks.kt
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyQuestions.kt
Jetsurvey/build.gradle
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Owl/app/src/main/java/com/example/owl/ui/utils/NetworkImage.kt
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt

New in `Accompanist 0.7.2-SNAPSHOT`

Migrate to rememberCoilPainter()

---

Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/build.gradle
JetNews/gradle/wrapper/gradle-wrapper.properties
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetcaster/gradle/wrapper/gradle-wrapper.properties
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetchat/gradle/wrapper/gradle-wrapper.properties
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsnack/gradle/wrapper/gradle-wrapper.properties
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Jetsurvey/gradle/wrapper/gradle-wrapper.properties
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt
Rally/buildSrc/src/main/java/com/example/compose/rally/buildsrc/dependencies.kt
Rally/gradle/wrapper/gradle-wrapper.properties

[All] Update AGP and Gradle

---

Jetcaster/app/src/main/java/com/example/jetcaster/data/PodcastFetcher.kt
Jetcaster/app/src/main/java/com/example/jetcaster/data/PodcastsRepository.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt

- All podcast feeds now load correctly. Previously we stop fetching as soon as any fetch failed.
- Increased the `offscreenLimit` for the podcast carousel. Removes the flash of new content coming in while scrolling.

[Jetcaster] Collection of small fixes

---

Jetsnack/app/src/main/java/com/example/jetsnack/ui/snackdetail/SnackDetail.kt
Jetsnack/app/src/main/res/values/strings.xml

Implemented missing feature SEE MORE
Before
After

[Jetsnack] Implement "see more" for Details if its too long

---

JetNews/app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsScreen.kt
JetNews/app/src/main/java/com/example/jetnews/utils/Modifiers.kt

[Jetnews] Improve large screen layouts

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/UserInput.kt

[Jetchat] Updates AnimatedVisibility usage

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/util/Colors.kt

I guess this fix is trivial that we do not need an issue to track. But if I should follow the contribution rules, please advise and I will do it.

Fix: constrast, constast, etc --> contrast

---

Jetsnack/app/src/main/java/com/example/jetsnack/ui/JetsnackNavGraph.kt

This fixes the content bottom padding

Pass modifier to NavGraph

---

Owl/app/src/main/java/com/example/owl/ui/OwlApp.kt

When navigating using the bottom nav bar.
This saves and restores scroll positions.

Enable state saving & restoration

---

.github/ci-gradle.properties
Crane/build.gradle
JetNews/app/build.gradle
JetNews/app/src/main/java/com/example/jetnews/JetnewsApplication.kt
Jetcaster/build.gradle
Jetchat/build.gradle
Jetsnack/build.gradle
Jetsurvey/build.gradle
Owl/build.gradle

[All] Restricts allWarningsAsErrors to CI and local properties. 

---

Crane/app/src/main/java/androidx/compose/samples/crane/details/DetailsActivity.kt
Crane/app/src/main/java/androidx/compose/samples/crane/home/CraneHome.kt

[Crane] Fix bug and clean up

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt
Jetcaster/app/src/main/java/com/example/jetcaster/util/Buttons.kt
Jetcaster/app/src/main/res/values/strings.xml

Talkback will now announce: "Following, double tap to unfollow" and "Not following, double tap to follow"

[Jetcaster] A11y improvements

---

JetNews/app/src/main/java/com/example/jetnews/ui/AppDrawer.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/PostContent.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/PostCardTop.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/PostCardYourNetwork.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/PostCards.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsScreen.kt
JetNews/app/src/main/res/values/strings.xml

1. Removing hardcoded strings
2. Refactor Sections Enum accepting StringResId
Issue: https://github.com/android/compose-samples/issues/612

[JetNews] Remove Hardcoded Strings

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/JetcasterApp.kt

Improving Connectivity Check Function Using Network Capabilities on SDK >= M

[Feature][Jetcaster] Connectivity Checking Improvement

---

Crane/app/src/androidTest/java/androidx/compose/samples/crane/calendar/CalendarTest.kt
Crane/app/src/main/java/androidx/compose/samples/crane/calendar/Calendar.kt
Crane/app/src/main/res/values/strings.xml

https://user-images.githubusercontent.com/6952116/126788665-22ab5537-8fca-4dba-86ae-d12097dee077.mp4

[Crane] Add semantics for Calendar

---

JetNews/app/src/main/java/com/example/jetnews/ui/components/JetnewsSnackbarHost.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeScreen.kt
JetNews/app/src/main/java/com/example/jetnews/utils/JetnewsSnackbarHost.kt

Update Snackbars according to mocks

[Jetnews] Snackbars large screens support

---

JetNews/app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/PostContent.kt
JetNews/app/src/main/java/com/example/jetnews/ui/components/AppNavRail.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeRoute.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeScreens.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/PostCards.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/utils/JetnewsIcons.kt
JetNews/app/src/main/res/values/strings.xml

[Jetnews] Better TopAppBar in large screens

---

JetNews/app/src/main/java/com/example/jetnews/utils/WindowSize.kt
JetNews/app/src/test/java/com/example/jetnews/utils/WindowSizeTest.kt

Updates the window breakpoints, mainly be widening the range that is considered `MEDIUM`.

[JetNews] Update window size breakpoints

---

JetNews/app/src/main/java/com/example/jetnews/ui/components/AppNavRail.kt

[Jetnews] Add space between NavRail icons

---

Jetchat/app/src/main/java/com/example/compose/jetchat/NavActivity.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/components/JetchatScaffold.kt
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt

[Jetchat] Using m3 alpha02 and NavigationDrawer

---

Crane/app/build.gradle
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/app/build.gradle
Jetcaster/app/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetchat/app/build.gradle
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetsnack/app/build.gradle
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/app/build.gradle
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Owl/app/build.gradle
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt

[All] Update tooling dependencies

---

Crane/app/src/androidTest/java/androidx/compose/samples/crane/details/CityMapViewTests.kt
Crane/build.gradle
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/app/build.gradle
JetNews/build.gradle
Jetcaster/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/components/JetchatScaffold.kt
Jetchat/build.gradle
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetsnack/build.gradle
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/app/build.gradle
Jetsurvey/build.gradle
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Owl/build.gradle
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt

This also updates spotless to 6.3, ktlint to 0.44.0, and some other
minor/bugfix library updates.

[All] Update to Compose 1.1.1

---

Reply/app/build.gradle
Reply/app/src/main/java/com/example/reply/MainActivity.kt
Reply/app/src/main/java/com/example/reply/ui/ReplyApp.kt
Reply/app/src/main/java/com/example/reply/ui/WindowSize.kt
Reply/app/src/main/java/com/example/reply/ui/WindowStateUtils.kt

- Setup size similar to [jetnews](https://github.com/android/compose-samples/blob/main/JetNews/app/src/main/java/com/example/jetnews/utils/WindowSize.kt) for adaptive sizing
- Setup Fold state similar to [JetCaster](https://github.com/android/compose-samples/blob/main/Jetcaster/app/src/main/java/com/example/jetcaster/ui/MainActivity.kt)
- Use proper navigation and content depending on the Screen Size and Fold state.

ReplyM3: Adaptive and Fold state setup

---

JetNews/app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt

Fixes #763
| **Before** | **After** |
|------------|-----------|
| <img src="https://dl3.pushbulletusercontent.com/qdL1mc31DdEgM9HKQ7LnUdYgTVOdgcTp/Screenshot_20220325-134910.png" width="400px"/>       |  <img src="https://dl3.pushbulletusercontent.com/HLEtVXE8Jd3L1PVhUsk3xndGaz8qY8gh/Screenshot_20220325-140239.png" width="400px"/>       |

Update BottomBar height within Article Screen

---

Crane/app/src/main/java/androidx/compose/samples/crane/base/BaseUserInput.kt
Crane/app/src/main/java/androidx/compose/samples/crane/base/CraneDrawer.kt
Crane/app/src/main/java/androidx/compose/samples/crane/calendar/CalendarActivity.kt
Crane/app/src/main/java/androidx/compose/samples/crane/home/CraneHome.kt
Crane/app/src/main/java/androidx/compose/samples/crane/home/HomeFeatures.kt
Crane/app/src/main/java/androidx/compose/samples/crane/home/SearchUserInput.kt
Crane/app/src/main/res/values/strings.xml

Fixes #612 - extract all strings to resources instead of them being hardcoded.

[Crane] Extract String resources

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
CODE_OF_CONDUCT.md

Adds:
* issue templates (bug reports and feature requests)
* pull request template
* CODE_OF_CONDUCT.md
Screenshots:

Add GitHub issue templates and CODE_OF_CONDUCT.

---

JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeScreens.kt

**Small Screen**
**Large Screen**

[JetNews] Remove "Popular on JetNews" Cards for large screens

---

Crane/app/src/main/java/androidx/compose/samples/crane/home/SearchUserInput.kt
Crane/build.gradle
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/app/build.gradle
JetNews/build.gradle
Jetcaster/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetchat/build.gradle
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetsnack/build.gradle
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/build.gradle
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Owl/build.gradle
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt

Update Compose to 1.2.0-alpha08
Update accompanist, ktlint, spotless & navigation-compose

[All] Update to Compose 1.2.0-alpha08

---

Jetsurvey/app/src/main/AndroidManifest.xml
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/WelcomeScreen.kt

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #757 🦕

[Jetsurvey]: Prevent email text field from going off screen.

---

Jetchat/app/src/main/java/com/example/compose/jetchat/NavActivity.kt

This PR fixes #784, by disabling inset consumption on the hosting activity via [`ComposeView.consumeWindowInsets = false`](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/package-summary#(androidx.compose.ui.platform.ComposeView).consumeWindowInsets()). This ensures that updated insets are propagated further down the view tree, so they can dodge the IME correctly.
Even on API 30 and above, the insets are not animated inside the fragment, which is a separate upstream issue.

[Jetchat] Fix insets by disabling consumption

---

Jetchat/app/build.gradle
Jetchat/app/src/main/java/com/example/compose/jetchat/theme/Typography.kt
Jetchat/app/src/main/res/values-v23/font_certs.xml
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt

Jetchat updates to latest Compose alpha

[JetChat] Adding Downloadable Fonts implementation

---

README.md

Removing reference to Android Views in Crane

Updated README to remove mention of Artic Fox

---

Crane/app/build.gradle
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt

This fixes #800 , by updating Dagger to the latest stable version.

Fix Crane Dagger lint

---

.github/workflows/Crane.yaml
.github/workflows/JetNews.yaml
.github/workflows/Jetcaster.yaml
.github/workflows/Jetchat.yaml
.github/workflows/Jetsnack.yaml
.github/workflows/Jetsurvey.yaml
.github/workflows/Owl.yaml

Reuse build workflow

---

Owl/README.md
Owl/app/build.gradle
Owl/app/src/main/java/com/example/owl/ui/course/CourseDetails.kt
Owl/app/src/main/java/com/example/owl/ui/courses/MyCourses.kt
Owl/app/src/main/java/com/example/owl/ui/courses/SearchCourses.kt
Owl/app/src/main/java/com/example/owl/ui/onboarding/Onboarding.kt
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt

Add item keys for Lazy layouts and animateItemPlacement animation
Clean up

Clean up Owl and add Lazy item keys & animateItemPlacement animation

---

.github/workflows/Crane.yaml

Fixes incorrect formatting in Crane.yml workflow. See failure in https://github.com/android/compose-samples/actions/runs/2504208239

[Crane] Fix workflow.

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/ConversationUiState.kt

[Jetchat] Unnecessary spread operator

---

Reply/app/src/main/java/com/example/reply/ui/theme/Theme.kt

fix: #900 
Removing deprecated `ViewCompat.windowInsetsController` with suggested `WIndowCompat.insetsController`

[Reply] Fix: Removed deprecated windowInsetController with WindowCompat.

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Reply is new addition to compose sample, so adding it to bug and feature request template for compose samples github.

Added Reply to bug and feature template for github

---

Reply/app/src/main/java/com/example/reply/ui/ReplyApp.kt
Reply/app/src/main/java/com/example/reply/ui/navigation/ReplyNavigationComponents.kt
Reply/app/src/main/java/com/example/reply/ui/theme/Shapes.kt
Reply/app/src/main/java/com/example/reply/ui/theme/Theme.kt
Reply/build.gradle

Added material 3 shapes to reply theming.
Also fixed #921 Where permanent navigation drawer shouldn't have back press button.

[Reply]: Added material 3 shapes and fix permanent drawer back button.

---

renovate.json

Taken from https://github.com/renovatebot/renovate/discussions/15285

Renovate: Group renovate and compose dependencies

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt

I am the creator of pull request #913. Since it is the first time I opened a pull request for Google and I did not follow the CLA request well, I accidentally introduced some mess into the commits I submitted. I created a new branch and fixed this problems according to your needs, with CLA properly signed. Sorry for the inconvenience. If there is a problem, please let me know. Thank you!

Fix a11y bugs of Jetcaster

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/UserInput.kt

Fix #883
Just removed the unused if-else condition.

Fixing: Remove Unused If-Else condition

---

.github/workflows/Crane.yaml
.github/workflows/JetNews.yaml
.github/workflows/Jetchat.yaml
.github/workflows/Owl.yaml
.github/workflows/Reply.yaml

Add matrix level and sample name to output folder.

---

README.md

Fix updateDeps.sh in README

---

Reply/app/build.gradle.kts
Reply/app/src/main/java/com/example/reply/ui/MainActivity.kt
Reply/app/src/main/java/com/example/reply/ui/ReplyApp.kt
Reply/app/src/main/java/com/example/reply/ui/ReplyListContent.kt
Reply/app/src/main/java/com/example/reply/ui/components/ReplyAppBars.kt
Reply/app/src/main/java/com/example/reply/ui/components/ReplyEmailListItem.kt
Reply/app/src/main/java/com/example/reply/ui/components/ReplyEmailThreadItem.kt
Reply/app/src/main/java/com/example/reply/ui/components/ReplyProfileImage.kt
Reply/app/src/main/java/com/example/reply/ui/navigation/ReplyNavigationComponents.kt
Reply/app/src/main/java/com/example/reply/ui/theme/Theme.kt
Reply/app/src/main/res/values/strings.xml
Reply/gradle/libs.versions.toml

- Added Dual pane support
- Accompanist adaptive lib
- Updated to latest material compose beta release
Fixing issue #997

Reply material updates and dual pane support

---

Crane/gradle/libs.versions.toml
JetNews/gradle/libs.versions.toml
Jetcaster/gradle/libs.versions.toml
Jetchat/gradle/libs.versions.toml
Jetsnack/gradle/libs.versions.toml
Jetsurvey/gradle/libs.versions.toml
Owl/gradle/libs.versions.toml
Reply/gradle/libs.versions.toml
scripts/libs.versions.toml

Fixes Compose preview not rendering when importing sample in AS

[All] Upgrade AGP to 7.3.0

---

Crane/build.gradle.kts
Crane/gradle/libs.versions.toml
JetLagged/build.gradle.kts
JetLagged/gradle/libs.versions.toml
JetNews/build.gradle.kts
JetNews/gradle/libs.versions.toml
Jetcaster/build.gradle.kts
Jetcaster/gradle/libs.versions.toml
Jetchat/build.gradle.kts
Jetchat/gradle/libs.versions.toml
Jetsnack/build.gradle.kts
Jetsnack/gradle/libs.versions.toml
Jetsurvey/build.gradle.kts
Jetsurvey/gradle/libs.versions.toml
Owl/build.gradle.kts
Owl/gradle/libs.versions.toml
Reply/build.gradle.kts
Reply/gradle/libs.versions.toml
scripts/libs.versions.toml

🤖 Update Dependencies

---

Crane/gradle/libs.versions.toml
JetLagged/gradle/libs.versions.toml
JetNews/gradle/libs.versions.toml
Jetcaster/gradle/libs.versions.toml
Jetchat/gradle/libs.versions.toml
Jetsnack/gradle/libs.versions.toml
Jetsurvey/gradle/libs.versions.toml
Owl/gradle/libs.versions.toml
Reply/gradle/libs.versions.toml
scripts/libs.versions.toml

[All] Update core library desugaring to 1.2.2

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/UserInput.kt

[JetChat] Fixing the send button not displaying properly

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/player/PlayerScreen.kt

To be merged when Compose Foundation reaches 1.4 stable

[Jetcaster] Add marquee to Jetcaster player

---

Jetchat/app/src/main/java/com/example/compose/jetchat/data/FakeData.kt

Tested on real Pixel 1 with API 30.
[Emoji 15](https://emojipedia.org/emoji-15.0/) 
[Emoji 13.1](https://emojipedia.org/emoji-13.1/) 😶‍🌫️
[Emoji 14](https://emojipedia.org/emoji-14.0/) 🫠

[Jetchat] Verifies modern emoji support in Compose 1.4.0

---

Owl/README.md

fixed coil link

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/RecordButton.kt

- Fixes `RecordButton` sending `onCancelled` continuously until the finger is raised, then still sending `onFinished`
- Refactors to not need `composed {}`

[Jetchat] Fix RecordButton sending cancellation callback continuously

---

Reply/app/src/main/AndroidManifest.xml
Reply/app/src/main/java/com/example/reply/ui/MainActivity.kt
Reply/app/src/main/java/com/example/reply/ui/ReplyApp.kt
Reply/app/src/main/java/com/example/reply/ui/ReplyListContent.kt
Reply/app/src/main/java/com/example/reply/ui/navigation/ReplyNavigationComponents.kt
Reply/app/src/main/java/com/example/reply/ui/theme/Theme.kt

https://github.com/android/compose-samples/assets/6952116/297752b1-cfe3-40e4-ad33-6b9c4c9d4b56
https://github.com/android/compose-samples/assets/6952116/6cea7c70-e9b7-459c-9f08-4e3c11e67ede
https://github.com/android/compose-samples/assets/6952116/b4a8c2c4-8c3c-4799-8ea5-328fc10a14bb
https://github.com/android/compose-samples/assets/6952116/d55f862c-08ab-4919-89b2-269afe0693f7

Add edge-to-edge support to Reply

---

Jetsnack/app/build.gradle.kts
Jetsnack/app/src/main/AndroidManifest.xml
Jetsnack/app/src/main/java/com/example/jetsnack/ui/MainActivity.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/DestinationBar.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/theme/Theme.kt
Jetsnack/app/src/main/res/values/themes.xml

Already supported E2E, changed implementation. Had to do some extra work for the top app bar to make sure it covered underneath the status bar.

[Jetsnack] Add edge to edge support

---

Jetchat/app/src/main/AndroidManifest.xml
Jetchat/app/src/main/java/com/example/compose/jetchat/NavActivity.kt

Supported already, simple migration

[Jetchat] Support edge to edge

---

.github/workflows/Crane.yaml
.github/workflows/JetLagged.yaml
.github/workflows/JetNews.yaml
.github/workflows/Jetchat.yaml
.github/workflows/Owl.yaml
.github/workflows/Release.yml
.github/workflows/build-sample.yml
.github/workflows/copy-branch.yml
.github/workflows/main.yml
.github/workflows/update_deps.yml

Need an action that updates dependencies on actions :P

Update actions dependencies

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/RecordButton.kt

[Jetchat] Fix broken record button behavior

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt

Fix Jetcaster showing an empty screen when the user is not following any podcasts.

[Jetcaster] Fix empty screen

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt

Cherry picked changes from #1309 by @florina-muntenescu but fixing CLA issue.
Closes #1309

[Jetcaster] Handling no podcast selected and extracting state for home

---

Jetcaster/wear/src/main/java/com/example/jetcaster/ui/home/HomeScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/library/LatestEpisodeViewModel.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/player/PlayerScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/player/PlayerViewModel.kt
Jetcaster/wear/src/main/res/values/strings.xml

Adds logic for enabling the button play/pause.

[Wear] Enable play/pause on the Player

---

Jetsnack/app/src/main/java/com/example/jetsnack/ui/theme/Theme.kt

Unnecessary state reads for colors, which never change.
Following official [M3 color scheme](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/ColorScheme.kt?q=androidx.compose.material3.ColorScheme)

[Jetsnack] Remove color states from the JetsnackColors

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt

[Jetcaster] Fixing the issue of content being obscured by the SystemNavigationBar

---

Jetcaster/wear/src/main/java/com/example/jetcaster/ui/components/SettingsButtons.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/player/PlayerScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/player/PlayerViewModel.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsViewModel.kt
Jetcaster/wear/src/main/res/values/strings.xml

- Add loading and empty state for Player
- Adds queue button to the screen and view model

Adds states for Player, adds queue button

---

Jetcaster/core/src/main/java/com/example/jetcaster/core/player/EpisodePlayer.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/player/MockEpisodePlayer.kt

So that the player speed can be reflected on the UI as it changes.So that the player speed can be reflected on the UI as it changes.So that the player speed can be reflected on the UI as it changes.

[Jetcaster]: Make player speed part of EpisodePlayerState

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/discover/Discover.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/shared/EpisodeListItem.kt

after category chip
https://github.com/android/compose-samples/assets/3973717/8bfe2fc4-3fa8-4010-b6d8-29860ccae43a
before podcast item
https://github.com/android/compose-samples/assets/3973717/eb1688cf-07f2-47d8-9102-7523c108b164
after podcast item
https://github.com/android/compose-samples/assets/3973717/e439c517-acce-42b8-803e-074b724d1136

Fix category ripple effect

---

Jetcaster/README.md
Jetcaster/wear/build.gradle
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/podcasts/PodcastsScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/podcasts/WearPreviewPodcasts.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/queue/QueueScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/queue/WearPreviewQueue.kt

- Adds previews to queue and podcasts
- Fixes README which had some redundant `[` `]`

[Wear] Adds previews to queue and podcasts

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/question/PhotoQuestion.kt

fix take photo crash due to uri not remembered

---

Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/JetcasterApp.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/Button.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/ButtonWithIcon.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeCard.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeDateAndDuration.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeDetails.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/ErrorState.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/Loading.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/NotAvailableFeature.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/PodcastCard.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/Seekbar.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/discover/DiscoverScreen.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/episode/EpisodeScreen.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/library/LibraryScreen.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/player/PlayerScreen.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/podcast/PodcastScreen.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/search/SearchScreen.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/theme/Color.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/theme/Theme.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/theme/Type.kt
Jetcaster/tv/src/main/res/values/strings.xml

This PR fixes several UX issues raised to the TV app.

[Jetcaster] Fix TV app UX issues

---

Jetcaster/glancewidget/src/main/java/com/example/jetcaster/glancewidget/Colors.kt
Jetcaster/glancewidget/src/main/java/com/example/jetcaster/glancewidget/JetcasterAppWidget.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/player/PlayerScreen.kt

- This pull request changes the initial d-pad focus on the player screen of the TV app. 
- This pull request also formats some files with spotlessApply.

[Jetcaster] change the initial focus on the player screen for TV app

---

Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/player/PlayerScreen.kt

[Jetcaster] Add PlayerScreen Album Default Image

---

.gitignore
Crane/.gitignore
JetLagged/.gitignore
JetNews/.gitignore
Jetcaster/.gitignore
Jetchat/.gitignore
Jetsnack/.gitignore
Jetsurvey/.gitignore
Owl/.gitignore
Reply/.gitignore

https://kotlinlang.org/docs/whatsnew20.html#new-directory-for-kotlin-data-in-gradle-projects

Gitignore .kotlin folder

---

Jetcaster/tv/src/main/java/com/example/jetcaster/tv/MainActivity.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/JetcasterApp.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeCard.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/PodcastCard.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/episode/EpisodeScreen.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/podcast/PodcastDetailsScreen.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/theme/Space.kt

Fix podcast art padding
Fix clipping on podcast screen
Fix navigation transition jumping around

[Jetcaster] Touch up the TV UI

---

Jetsnack/app/src/main/java/com/example/jetsnack/ui/snackdetail/SnackDetail.kt

https://github.com/user-attachments/assets/f793fd86-fe65-4164-af68-9f1a9b41b184

Add animating background gradient on JetSnack

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/Conversation.kt

Add Drop feature for JetChat
https://github.com/user-attachments/assets/c4828128-0bc5-471f-85fb-eba2ad9930e8

Implement Drop feature

---

JetLagged/app/src/main/AndroidManifest.xml
JetLagged/app/src/main/java/com/example/jetlagged/JetLaggedDrawer.kt

This uses a PredictiveBackHandler and collects the flow of back events to manipulate the translation. I created separate openDrawer and closeDrawer functions to reuse the code in both toggleDrawerState and in the PredictiveBackHandler implementation.

Added predictive back animation to drawer

---

.github/workflows/Release.yml

Version not found, causing workflow error. [link](https://github.com/android/compose-samples/actions/runs/8928913208)
Updated create-release@v4 to @v1.
Additionally, updated the Jetcaster asset path.

Update action version and asset path

---

JetLagged/gradle/libs.versions.toml
JetNews/app/build.gradle.kts
JetNews/gradle/libs.versions.toml
Jetcaster/gradle/libs.versions.toml
Jetchat/gradle/libs.versions.toml
Jetsnack/gradle/libs.versions.toml
Reply/gradle/libs.versions.toml
scripts/libs.versions.toml

Removes accompanist/systemuicontroller from all usages in compose-samples

Remove accompanist/systemuicontroller

---

JetLagged/gradle/libs.versions.toml
JetNews/gradle/libs.versions.toml
Jetcaster/gradle/libs.versions.toml
Jetchat/gradle/libs.versions.toml
Jetsnack/gradle/libs.versions.toml
Reply/gradle/libs.versions.toml
scripts/libs.versions.toml

Removes accompanist/pager from all usages in compose-samples

Remove accompanist/pager

---

JetLagged/app/build.gradle.kts
JetLagged/gradle/libs.versions.toml
JetNews/gradle/libs.versions.toml
Jetcaster/gradle/libs.versions.toml
Jetchat/gradle/libs.versions.toml
Jetsnack/gradle/libs.versions.toml
Reply/gradle/libs.versions.toml
scripts/libs.versions.toml

Removes all usages of accompanist/flowlayout from projects in compose-samples

Remove accompanist/flowlayout

---

.github/workflows/default-check.yml

Makes sure we pass required checks when making changes to non-sample files

Add a new check
