android/compose-samples

JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsApp.kt

This tiny PR makes the drawer buttons take up all horizontal space instead of the awkward left-aligned behaviour they have currently.
Before | After
--- | ---

Make drawer buttons take up all horizontal space

---

Jetcaster/README.md

Fixes typo in `README.md`
`Data` -> `Date`

Fix typo in date time section of Jetcaster README

---

Jetsnack/app/src/main/java/com/example/jetsnack/ui/utils/Insets.kt

[Jetsnack] Provide default value for `InsetsAmbient`. 

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInSignUp.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignUpScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/WelcomeScreen.kt

added imeAction for email & password text field on the Welcome screen, Signup screen, and Sign-in screen. 
1. Welcome Screen
When you tap enter on the welcome screen it will perform the same action as tapping on continue.
2. Sign-in Screen
When you tap enter on email it will transfer focus to the password text field. When you tap enter on the password text
field it will call onSignInSubmitted
3. Signup Screen
The first two text field will transfer focus, the last one will call onSignUpSubmitted
example on welcome screen.

add imeAction to email & password text field

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyScreen.kt

The Jetsurvey result is not scrollable on landscape or split-screen mode, so I replaced Column with ScrollableColumn and now it's scrollable.
like this.

[Jetsurvey] Add ScrollableColumn to SurveyResult

---

.github/workflows/Crane.yaml
.github/workflows/JetNews.yaml
.github/workflows/Jetcaster.yaml
.github/workflows/Jetchat.yaml
.github/workflows/Jetsnack.yaml
.github/workflows/Jetsurvey.yaml
.github/workflows/Owl.yaml
.github/workflows/Rally.yaml

I have noticed that I do not have directory `~/.gradle/caches/jars-3` locally.
On my computer `ls ~/.gradle/caches/ | grep jars` returns jars-8 only.
Reference: https://github.com/gradle/gradle/blob/1e3ce9cf4394e3e0e290ef4a647ffb5e0d1343dc/subprojects/core/src/main/java/org/gradle/internal/classpath/DefaultClasspathTransformerCacheFactory.java#L46
All samples use Gradle 6.6 at the moment:
`grep -R distributionUrl`
> Owl/gradle/wrapper/gradle-wrapper.properties:distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-bin.zip
Jetsnack/gradle/wrapper/gradle-wrapper.properties:distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-bin.zip
JetNews/gradle/wrapper/gradle-wrapper.properties:distributionUrl=https\://services.gradle.org/distributions/gradle-6.6-bin.zip …

Update Gradle cache version to jars-8

---

JetNews/.gitignore
JetNews/app/build.gradle
JetNews/app/src/androidTest/java/com/example/jetnews/HomeScreenSnackbarTest.kt
JetNews/app/src/androidTest/java/com/example/jetnews/JetnewsUiTest.kt
JetNews/app/src/androidTest/java/com/example/jetnews/TestHelper.kt
JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsApp.kt
JetNews/app/src/main/java/com/example/jetnews/ui/SwipeToRefresh.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/PostContent.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/PostCardTop.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsScreen.kt
JetNews/app/src/main/res/values/strings.xml
JetNews/build.gradle
JetNews/gradle/wrapper/gradle-wrapper.properties

Update snackbar in [HomeScreen] to not restart when posts changes but
the error remains false (previously it would flicker due to a restart)
Change workaround in SwipeToRefresh to not crash in alpha03. This was
caused by the behavior change of [onCommit].
Various renames from alpha01-alpha03

Update JetNews to alpha03.

---

Jetcaster/app/build.gradle
Jetcaster/app/src/main/java/com/example/jetcaster/ui/MainActivity.kt
Jetcaster/app/src/main/res/values/themes.xml

They're unnecessary since we're a Compose-only app

[Jetcaster] Remove AppCompat + MDC

---

Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/build.gradle
Jetcaster/app/build.gradle
Jetcaster/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetchat/app/build.gradle
Jetchat/build.gradle
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetsnack/app/build.gradle
Jetsnack/build.gradle
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/app/build.gradle
Jetsurvey/build.gradle
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Owl/app/build.gradle
Owl/build.gradle
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt
Rally/app/build.gradle
Rally/build.gradle
Rally/buildSrc/src/main/java/com/example/compose/rally/buildsrc/dependencies.kt

Shouldn't build until alpha04, Accompanist 0.3.0 ang AGP13 are released

WIP: alpha04 release

---

JetNews/app/build.gradle
JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsApp.kt
JetNews/app/src/main/java/com/example/jetnews/ui/SwipeToRefresh.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/PostContent.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/PostCardTop.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/PostCardYourNetwork.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/PostCards.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/SelectTopicButton.kt
JetNews/app/src/main/java/com/example/jetnews/utils/ProduceUiState.kt
JetNews/build.gradle

Changes:
- Use new produceState API in launchUiStateProducer
- Rename launchUiStateProducer to produceUiState to match naming
- Change launchInComposition to new API LaunchedTask
- Replace Box/Surface with new Box import
- Update modifiers for Text composable to work with new layout rules
- Update to use new AmbientContentColor and AmbientEmphasisLevels
Bugfix:
- Fix size of error case in [HomeScreenErrorAndContent], avoiding
the swipe to refresh drawing in the incorrect place.

Bump JetNews to alpha05

---

Crane/app/src/main/java/androidx/compose/samples/crane/home/MainActivity.kt
Crane/app/src/main/java/androidx/compose/samples/crane/home/SearchUserInput.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/discover/Discover.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/components/AnimatingFabContent.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/JumpToBottom.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/profile/Profile.kt
Owl/app/src/main/java/com/example/owl/ui/onboarding/Onboarding.kt
Rally/app/src/main/java/com/example/compose/rally/ui/components/RallyAnimatedCircle.kt

The label field is used to identify the PropKeys when inspecting the
animations in the Animation Preview.
Also add a couple of previews to Crane and Jetchat that contain
transition animations, which can be open in the Animation Preview.

Set label field to transition animation PropKeys

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyFragment.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyQuestions.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyState.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyViewModel.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/theme/Color.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/theme/Theme.kt
Jetsurvey/app/src/main/res/values/strings.xml

* Changing the progress indicator, the previous and next buttons and the question text.
* The next button is now enabled only when an answer was selected
* Capitalising button texts throughout the app.

[Jetsurvey] Implementing the redesign of the survey screen (part 1)

---

README.md

Hello,
I want to propose 2 changes to the README:
- Updated recommended AS canary version to Arctic Fox 2020.3.1.
- Add a link that takes directly to the AS canary download page.
About the first point, in my opinion I'd completely remove the version from the text and just leave it as "the lastest Canary version of Android Studio).

README: Update AS Canary version & added download link

---

Jetcaster/app/src/main/java/com/example/jetcaster/Graph.kt
Jetcaster/app/src/main/java/com/example/jetcaster/data/PodcastStore.kt
Jetcaster/app/src/main/java/com/example/jetcaster/data/PodcastsRepository.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt
Jetcaster/app/src/main/java/com/example/jetcaster/util/DynamicTheming.kt
Jetcaster/app/src/main/java/com/example/jetcaster/util/GradientScrim.kt
Jetcaster/app/src/main/java/com/example/jetcaster/util/Pager.kt
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetcaster/gradle/wrapper/gradle-wrapper.properties

Upgrade to alpha09 snapshot
Upgrade to Gradle 6.8
Remove unused imports
Apply Compose API changes

[Jetcaster] Bump to alpha09 snapshot

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/ConversationFragment.kt

Happens when the device is in landscape.

[Jetchat] Fix UI covered by navigation bars

---

Owl/app/src/androidTest/java/com/example/owl/ui/NavigationTest.kt
Owl/app/src/main/java/com/example/owl/ui/MainActivity.kt
Owl/app/src/main/java/com/example/owl/ui/NavGraph.kt
Owl/app/src/main/java/com/example/owl/ui/OwlApp.kt
Owl/app/src/main/java/com/example/owl/ui/course/CourseDetails.kt
Owl/app/src/main/java/com/example/owl/ui/courses/Courses.kt
Owl/app/src/main/java/com/example/owl/ui/utils/Navigation.kt
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt

Navigation was using a snapshot build (7187420) which is not out yet. To make the next release easier, I'm reverting as there's not reason to sync with it.

Revert "[Owl] Nested navigation"

---

JetNews/app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/PostContent.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/PostCardTop.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/SelectTopicButton.kt

Updated UI components to match current design
https://github.com/android/compose-samples/issues/458
- **Line height in article doesn't match spec**
Before
After
- **Spacing on article title on hero card on Home screen is off from spec**
Before
After
- **Heart icon article bottom app bar should be a Like icon**
Before
After
- **Divider lines missing between Interest list items**
- **Spacing between Interest list items doesn't match spec**
- **Add interest button doesn't match spec**
Before
After
- **EXTRA: Tab style doesn't match design**
Before
After

[Jetnews] UI polish bugs #458

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInSignUp.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/WelcomeScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyQuestions.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/theme/Theme.kt

Fixed first reported issues for Jetsurvey application
https://github.com/android/compose-samples/issues/460
**Login/signup screen**
•	 TextField corners on Login/Signup should be more round (12.dp versus 4.dp)
_Pending: Feature not yet implemented by Material component OutlinedTextField_
•	  Spacing above "Sign in" text should be 64.dp
•	  Space between "Sign in" and email text field should be 20.dp
_OutlinedTextField has an 8 dp top padding so I adjusted the space to 12 dp_
•	  Space between Continue button and "or" should be 28.dp (text baseline aligned)
Before
After
**Base elements question polish**
•	  Close X mark should be on right
•	  Close X mark should be vertically centered with " of " text
•	  Close X mark edge should align with end of progress bar
•	  Spacing between progress …

[Jetsurvey] UI polish bugs

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyQuestions.kt

Currently the resolved height of the image will be 0, which results in Coil not being able to load anything. This PR fixes that by setting a minimum height on the image, which allows Coil to know a initial height.
Also fixed usage of `fillMax[*]` to `fillMaxParent[*]` for LazyColumn items.

[Jetsurvey] Fix constraints for LazyColumn items

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyQuestions.kt

Preview image stop showing after migrating to rememberCoilPainter
https://github.com/android/compose-samples/issues/460
Taken photo should be clipped, keep size of photo frame the same
Before
After

[Jetsurvey] Photo was not showing with rememberCoilPainter

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/Survey.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyFragment.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyQuestions.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyRepository.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyViewModel.kt
Jetsurvey/app/src/main/res/values/strings.xml

https://github.com/android/compose-samples/issues/460
- No motion for change in progress indicator -- Added animation
**Pick a date question**
- Date button should be exposed dropdown
- Date picker says "Selected date" on open instead of the selected date
- Selected date should be value of exposed dropdown
Before
After
**Scale selfies question** 
- Slider design implementation not according to spec
-  On page load, mid-point selected by default for slider
Before
After

[Jetsurvey] Issue460/date slider photo

---

Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/Snacks.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/Profile.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/cart/Cart.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/search/Categories.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/snackdetail/SnackDetail.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/theme/Theme.kt
Jetsnack/app/src/main/res/values/strings.xml

https://github.com/android/compose-samples/issues/487
Home
-  Text in "Add to cart" button not centered
Before
After
-  Empty state for Profile should use placeholder graphic
Before
After
-  Second row of cards should use pink gradients (if possible make them alternate between blue and pink)
-  Elements should be left aligned with 24.dp margin/guide
Before
After
-  Checkout button ripple should be across whole button -- FIXED
**Item details**
-  Item page background gradient should be Gradient 2-2 (see spec) -- Spec has a gradient called tornado1
-  Padding between Details and Ingredients should be 16.dp
Before
After
Search
Incorrect background gradients used in dark theme
Before
After

[Jetsnack] UI Polish

---

Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/Filters.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/GradientTintedIconButton.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/QuantitySelector.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/theme/Theme.kt

https://github.com/android/compose-samples/issues/487
**Home**
-  Filter chips "pressed" and "selected" state is not to spec
-  Incorrect gradient borders on chips in dark theme
Before
After
**Cart**
-  The quantity + and - buttons should have same click state as filter chips
Before
After

[Jetsnack] Create styles for different button states

---

JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsScreen.kt

To test: 
- Navigate to Interests screen
- Turn on Talkback
- Turn on navigation by headings, by swiping repeatedly with three fingers
- Swipe up & down to navigate from header to header

[Jetnews] Mark headings in interests screen for accessibility services

---

JetNews/app/src/main/java/com/example/jetnews/data/posts/impl/PostsData.kt

Fixed the app crash when scrolling the article screen of "Collections and sequences in Kotlin"
Issue link : https://github.com/android/compose-samples/issues/510

[JetNews] Fixed the app crash when scrolling the article screen of "Collections and sequences in Kotlin"

---

Owl/app/src/main/java/com/example/owl/ui/utils/NetworkImage.kt

[Owl] Fix image sizes.

---

Owl/app/src/androidTest/java/com/example/owl/ui/fakes/ProvideTestImageLoader.kt

The TestImageLoader was set to return the same drawable instance for every request. This causes issues though as Drawables are stateful, and therefore can't be used in multiple places at once.
Fixed by returning a new instance for each request. Also remembered the image loader for a small perf improvement.
Fixes #537

[Owl] Fix tests never ending

---

LICENSE

The LICENSE file should not contain the custom notice for Apache 2.0.
This commit replaces the custom notice with the templated version and
brings the contents of LICENSE file to match
https://www.apache.org/licenses/LICENSE-2.0.txt
Fixes #545.

Fix custom notice in LICENSE file

---

Crane/app/build.gradle
Crane/build.gradle
Crane/buildSrc/build.gradle.kts
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/build.gradle
Jetcaster/build.gradle
Jetcaster/buildSrc/build.gradle.kts
Jetchat/build.gradle
Jetsnack/build.gradle
Jetsnack/buildSrc/build.gradle.kts
Jetsurvey/build.gradle
Jetsurvey/buildSrc/build.gradle.kts
Owl/build.gradle
Owl/buildSrc/build.gradle.kts
Rally/build.gradle
Rally/buildSrc/build.gradle.kts

Jcenter is now read only and no longer needed. 
Added maven central where needed.
Use Volley 1.2.0 which is available on maven.google.com (required as a dep of the Maps SDK)

Remove jcenter

---

CONTRIBUTING.md

Best I can tell, the `dev_XX` branches are no longer in use.

Update info on contributing to reference `main` branch

---

Owl/app/src/main/java/com/example/owl/ui/NavGraph.kt

Changes a small typo in `Owl`'s `NavGraph.kt`: `rom` -> `from`

[Owl] Fix typo in NavGraph

---

Jetsnack/app/src/main/java/com/example/jetsnack/ui/theme/Theme.kt

Adds a `copy` method to `JetsnackColors`, which is used to copy the passed in `colors` when providing `JetsnackColors`.
This avoids `update()` mutating the `colors` passed in as a parameter, which would manifest itself as a bug where switching the system between dark theme and light theme would only work the first time, as `DarkColorPalette` and `LightColorPalette` would overwrite each other. (right now that bug doesn't occur, since `MainActivity` is being recreated upon configuration changes).
This fixes #584, which also has more context.

[Jetsnack] Avoid mutating colors parameter

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyFragment.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyQuestions.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyViewModel.kt

Fixed the app crash on changing the selected date for the date selection question.
Issue link: https://github.com/android/compose-samples/issues/512

[Jetsurvey] fixed app crash on changing date selection

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyQuestions.kt

Let's not be rude. We shouldn't show the permissions dialog without previous warning. That's a bad UX since the user is likely to deny it without any context.

[Jetsurvey] Improve permissions UX

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt

Extracted the Category podcasts and Episode lists to separate composables
https://github.com/android/compose-samples/issues/553 (Not 100% sure if it's related)

[jetcaster] Fixed the laggy scrolling

---

scripts/checksum.sh

Finishes a comment in `checksum.sh` describing why the file hashes are sorted.

Finish checksum.sh sentence

---

JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsApp.kt
JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsNavGraph.kt

Fixes the state saving (via `rememberSaveable`) throughout the app.
Per the design, we conditionally want to allow the drawer to be shown based on the size of the screen. With the current approach we conditionally passed `null` or the drawer content to a top-level `Scaffold`, which would then allow the drawer to be hidden or shown. If we don't want the drawer to be shown, we instead show the nav rail.
This approach has a subtle problem due to the [implementation of `Scaffold`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/commonMain/kotlin/androidx/compose/material/Scaffold.kt;l=194;drc=0868ad90686faea3d86e395fb3758e8a1bbbeaac): when we switch the drawer content between `null` and non-null, we are changing the location of where …

[JetNews] Fix state saving with drawer

---

JetNews/app/build.gradle
JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsApp.kt
JetNews/app/src/main/java/com/example/jetnews/utils/WindowSize.kt

Converts the decision on whether to use the navrail or the drawer to use the current window metrics, as opposed to a top-level `BoxWithConstraints`.
There are three other places where we are currently calling `getWindowSize`:
- Deciding between which home screens to use
- Deciding what interests tab layout to use
- Deciding what interests to use
This PR doesn't change any of those places, but we may want to adjust some (or all) of them to use the current window metrics instead of nested `BoxWithConstraints`.
We also could pass down the window size class manually, or have each of those places individually call `rememberWindowSizeState()`.

[JetNews] Convert navrail/drawer decision to use currentWindowMetrics

---

JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsApp.kt
JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsNavGraph.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeRoute.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsRoute.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsScreen.kt
JetNews/app/src/main/java/com/example/jetnews/utils/WindowSize.kt

This PR refines the window size class handling, primarily by resolving that size class in one place, in the top-level `JetnewsApp`.
I also fixed the issue where the list and detail layout was being used for the `Medium` size class, whereas we want to show either the list or detail at the `Medium` breakpoint.
A couple notes:
- I am passing down both a `WindowSize` and a resolved `Boolean` flag in some places. My rationale there is making a certain decision in exactly once place, and passing down that resolved value. So, therefore we create `isDrawerActive` in exactly one place, and then pass it down, while also passing down the raw `WindowSize`, because some screen may make an unrelated decisions using the size class (1 or 2 columns somewhere).
- The `Medium` size class design is not …

[JetNews] Adjust medium behavior

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt

fix : fixing the fact that we were no able to move from CategoryPodcast to EpisodeList with Talkback by removing unnecessary (?!) LazyRow
feat: merge podcast category image with podcast title, this way also podcast title is read before moving to the "follow button".
feat : improve UX by setting Button semantic role to play image button

[JetCaster] improve a11y

---

JetNews/app/src/main/java/com/example/jetnews/utils/WindowSize.kt

Removes the subscription to `currentWindowMetrics` flow, in favor of always performing the synchronous calculation.
The currently released version of `WindowManager` (`1.0.0-beta02`) has an [issue](https://issuetracker.google.com/issues/198562467) with `currentWindowMetrics` flow, where the new window metrics won't be properly propagated after a configuration change, if the activity is handling the configuration change.
This is reproducible with JetNews on Chrome OS, if the activity is adjusted to handle all configuration changes:
Resizing the window never propagates a new window metrics value, so the app doesn't change layouts.
This bug was fixed with a [workaround](https://cs.android.com/androidx/platform/frameworks/support/+/adbfb31c7699e5bebde57e625916979bd32de242), but this …

[JetNews] Replace currentWindowMetrics flow with synchronous calculation

---

JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsApp.kt
JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsNavGraph.kt
JetNews/app/src/main/java/com/example/jetnews/ui/article/ArticleScreen.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeRoute.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsRoute.kt
JetNews/app/src/main/java/com/example/jetnews/ui/interests/InterestsScreen.kt

[Jetnews] Consolidate compact and medium layouts

---

.github/workflows/Crane.yaml
.github/workflows/JetNews.yaml
.github/workflows/Jetcaster.yaml
.github/workflows/Jetchat.yaml
.github/workflows/Jetsnack.yaml
.github/workflows/Jetsurvey.yaml
.github/workflows/Owl.yaml

Adds `assembleRelease` to the build steps for all projects.
This will ensure that changes can't be made that prevent `release` variants of apps from failing to compile, although it doesn't verify any runtime behavior (i.e. `release` variants could crash on startup).

Add assembleRelease to CI steps

---

Crane/app/src/main/java/androidx/compose/samples/crane/base/CraneTabs.kt

The Tab's on Crane were current don't animate the selection changes, and the ripple shape is currently square - extending past the size of the rounded border. 
This PR changes the ripple to be clipped to the `RoundedCornerShape` and animates the tab selection based on the docs [here](https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#TabRow(kotlin.Int,androidx.compose.ui.Modifier,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,kotlin.Function1,kotlin.Function0,kotlin.Function0)).
| Before | After |
|-------|-------|
|![Crane_TabRow_Before](https://user-images.githubusercontent.com/9973046/159972088-48541490-0bda-46af-b1bf-19d7d2fdb08a.gif)| ![Crane_TabRow_Improvements](https://user-images.githubusercontent.com/9973046/159972154-b7 …

[Crane] Improved Tab selector ripple and added animation transition between tabs

---

Crane/app/src/main/java/androidx/compose/samples/crane/calendar/CalendarActivity.kt

The back arrow was black on purple, this PR changes it to use `onSurface` color. 
| Before | After |
|----|----|
| ![image](https://user-images.githubusercontent.com/9973046/160102286-2d2ceecb-3d7f-4972-8fee-32d4f59ff829.png) | ![Screenshot_1648203482](https://user-images.githubusercontent.com/9973046/160102221-54a01fa7-9f5e-4740-8785-3a1538f2a880.png) |

[Crane] Change back arrow to be onSurface color 🔙

---

Crane/app/src/main/java/androidx/compose/samples/crane/base/BaseUserInput.kt

Previously when clicking on the "Choose Destination" text in the C
rane app, it would let you start editing the hint.  This PR introduces a change that uses `decorationBox` to draw the hint as a separate `Text` field, similar to the way in which Material `TextField` works. 
| Before | After |
|-------|-------|
| https://user-images.githubusercontent.com/9973046/160439435-405447cf-4b1d-4d91-aa4d-13c18b0efcc7.mp4 | https://user-images.githubusercontent.com/9973046/160439498-4b312a1b-c8cc-4991-8fac-681f839a1f54.mp4  |

[Crane] Fix issue with "Choose Destination" text being editable

---

JetNews/build.gradle
scripts/upgrade_samples.sh

This PR adds a script that will search all the sample projects for Compose versions and update them all at the same time to either a release like 1.2.0-alpha06 or a snapshot. In order to achieve this I had to add the ability for JetNews to use a snapshot version.
Used with:
`scripts/upgrade_samples.sh`

[All] Add a script to update all sample Compose versions

---

Crane/app/src/main/java/androidx/compose/samples/crane/calendar/Calendar.kt
Crane/app/src/main/java/androidx/compose/samples/crane/calendar/CalendarActivity.kt
Crane/app/src/main/java/androidx/compose/samples/crane/home/CraneHome.kt
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/Home.kt
Jetsnack/build.gradle
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInSignUp.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignUpScreen.kt
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt

Fixes new lint error when you leave the `Scaffold` `contentPadding` parameter unused. 
I switched out some implementations of window insets to the recommended version for this.
- With LazyLists I used `contentPadding` so the content still scrolls under the edge of the screen
- With other layouts just `modifier.padding(contentPadding)` is enough

[All] Update to Compose 1.2.0-alpha07

---

Jetsnack/app/src/main/java/com/example/jetsnack/ui/snackdetail/SnackDetail.kt

Fixes janky scrolling on the JetSnack details page.
Fixes #231 
It should not be necessary to recompose just to relayout a page. JetSnack has a collapsing toolbar like layout on the details page, it shrinks the image and moves the title text up on scroll. This was previously done using in composition but by moving the read of the scroll value into a lambda, we can read the value only during layout and skip the composition phase entirely.

[JetSnack] Move scroll state reads into layout phase via lambdas

---

.github/CODEOWNERS

Adding CODEOWNERS per sample and overall codeowners. This will help with automatic assigning of code reviews to people.

Adding CODEOWNERS file for PR reviews

---

.github/blunderbuss.yml

Create blunderbuss.yml, for auto assignment of new open issues to @android/compose-devrel team members.

Create blunderbuss.yml config to assign issues to compose devrel

---

Crane/app/src/main/java/androidx/compose/samples/crane/calendar/CalendarScreen.kt
Crane/app/src/main/java/androidx/compose/samples/crane/home/MainActivity.kt

Update paddings in landscape mode for main and calendar screens.
----
- Before
- After

[Crane] Paddings in landscape mode

---

Jetsurvey/app/build.gradle
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/Survey.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyFragment.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyQuestions.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyRepository.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyViewModel.kt
Jetsurvey/app/src/test/java/com/example/compose/jetsurvey/survey/SurveyViewModelTest.kt
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt

This fixes #745. The answers to date questions now store the date in
milliseconds and all calculations are based on UTC.

[Jetsurvey] Updated date handling to use UTC only

---

Jetcaster/README.md

Since WindowInsets and Coil are no longer supported by Accompanist, they have been removed from app dependencies, but still remain in Readme.
```kt
object Accompanist {
const val version = "0.24.9-beta"
const val pager = "com.google.accompanist:accompanist-pager:$version"
}
```
There is only Pager as Accompanist in the app dependencies.

[Jetcaster] Fix Readme out-of-date

---

.github/workflows/Crane.yaml
.github/workflows/JetNews.yaml
.github/workflows/Jetcaster.yaml
.github/workflows/Jetchat.yaml
.github/workflows/Jetsnack.yaml
.github/workflows/Jetsurvey.yaml
.github/workflows/Owl.yaml

Reverts android/compose-samples#819
It breaks https://github.com/android/compose-samples/actions/runs/2370439106

Revert "Reuse build workflow"

---

.github/workflows/Crane.yaml
.github/workflows/JetNews.yaml
.github/workflows/Jetcaster.yaml
.github/workflows/Jetchat.yaml
.github/workflows/Jetsnack.yaml
.github/workflows/Jetsurvey.yaml
.github/workflows/Owl.yaml

* Reuse workflows (Re-revert 17db314ff3fd767d31c313de52ec6b346bc98677)
* Remove `runs-on` and `timeout-minutes` from `JetNews.yml` and inherits values from the reusable workflow
Fixes #817

Remove runs-on and timeout-minutes config from JetNews.yml

---

Jetchat/README.md
Jetchat/app/src/main/java/com/example/compose/jetchat/profile/Profile.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/profile/ProfileFragment.kt
Jetchat/app/src/main/res/layout/fragment_profile.xml

Add the Nested scrolling interop API to Jetchat Profile screen, to showcase the proper usage of this experimental API in the scenario of having a View parent and a composable child. Steps done:
- Refactor ProfileFragment to use an old school XML layout, with a CoordinatorLayout, CollapsingToolbarLayout that hosts a ComposeView for the `JetchatAppBar` composable and a separate ComposeView that will host the `ProfileScreen` composable
- Set the correct Fragment layout and composables using the guidelines on View/Compose interoperability
- Hook up the nested scrolling interop connection between the View parent and composable childeren via `rememberNestedScrollInteropConnection()`  to enable the collapsing behavior and scrolling connection between all these elements
- Minor clean up
More …

[Jetchat] Add Nested scrolling interop API

---

.github/workflows/Crane.yaml
Crane/README.md
Crane/app/build.gradle
Crane/build.gradle
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt

Adding [secrets-gradle-plugin](https://github.com/google/secrets-gradle-plugin) to handle reading key/values from `local.properties`.

Adding secrets-gradle-plugin.

---

Crane/README.md
Crane/app/build.gradle
Crane/local.defaults.properties

Add `local.defaults.properties` file so that Crane can build and run without a googleMapsKey. A key is still necessary to see the map load, however. See Crane's README for more info.
----
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #845 🦕

[Crane] Add default properties file.

---

.github/workflows/JetNews.yaml
.github/workflows/Jetchat.yaml
.github/workflows/Jetsnack.yaml
.github/workflows/Jetsurvey.yaml
.github/workflows/Owl.yaml

Adding `workflow_dispatch` trigger to all workflows so that they can be manually run from the Actions tab. A number of workflows already supported this (like Crane). This would allow us to build samples from any branch without having to open a pull request.

Add support for workflow_dispatch on all GH workflows.

---

Crane/app/src/main/java/androidx/compose/samples/crane/base/ExploreSection.kt
Crane/app/src/main/java/androidx/compose/samples/crane/home/CraneHome.kt

| Before  |  After |   
|---|---|
| https://user-images.githubusercontent.com/9973046/173384749-7729f3e0-08ad-427f-b0a1-fbebc01309a0.mp4 |  https://user-images.githubusercontent.com/9973046/173383605-d17c5339-0453-49b6-b066-ff5bbad91bfe.mp4 |

[Crane] Use AnimatedContent to transition between content states.

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyFragment.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyScreen.kt

Added two usages of AnimatedContent into JetSurvey.
1. Switching between Question Content
| Before  |  After |   
|---|---|
|![Survey_Questions_No_animation_Demo_Mode](https://user-images.githubusercontent.com/9973046/173243765-ce3ece43-22b8-41ca-954f-153e922e27dc.gif) | ![End_Questions_optimized](https://user-images.githubusercontent.com/9973046/173244109-18c88ca1-3dca-4926-adb1-cf75346e07c0.gif) |
3. Switching from questions to results
| Before  |  After |   
|---|---|
| ![End_Congrats_Before_DemoMode](https://user-images.githubusercontent.com/9973046/173244342-6ac00cdd-55ff-4c7e-9956-2369e7d77e8e.gif) | ![End_Congrats_Final_Demo_Mode](https://user-images.githubusercontent.com/9973046/173244394-1662d8e4-0b43-4a26-9eee-1bd56ec3c10a.gif) |
Animate the changes between different question …

[JetSurvey] Use AnimatedContent to slide in and out changes between questions

---

Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt
scripts/upgrade_samples.sh

Updating all samples to use the latest version ([1.2.0-rc02](https://developer.android.com/jetpack/androidx/releases/compose#1.2.0-rc02)) of Compose.

[All] Update to Compose 1.2.0-rc02

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/UserInput.kt

Fixing disabled stickers tab

---

Crane/app/build.gradle
Crane/buildSrc/src/main/java/com/example/crane/buildsrc/Dependencies.kt
JetNews/app/build.gradle
JetNews/build.gradle
Jetcaster/app/build.gradle
Jetcaster/buildSrc/src/main/java/com/example/jetcaster/buildsrc/dependencies.kt
Jetchat/app/build.gradle
Jetchat/buildSrc/src/main/java/com/example/compose/jetchat/buildsrc/dependencies.kt
Jetsnack/app/build.gradle
Jetsnack/buildSrc/src/main/java/com/example/jetsnack/buildsrc/Dependencies.kt
Jetsurvey/app/build.gradle
Jetsurvey/build.gradle
Jetsurvey/buildSrc/src/main/java/com/example/compose/jetsurvey/buildsrc/dependencies.kt
Owl/app/build.gradle
Owl/buildSrc/src/main/java/com/example/owl/buildsrc/Dependencies.kt
scripts/upgrade_samples.sh

Updating samples to use latest Compose Compiler 1.2.0 and Kotlin 1.7.0. This is the start of [independent versioning](https://android-developers.googleblog.com/2022/06/independent-versioning-of-Jetpack-Compose-libraries.html) of the compiler and various Compose libraries.
Also updated Room on Jetchat to 2.5.0-alpha02 which supports Kotlin 1.7.0.

[All] Update Compose Compiler to 1.2.0

---

JetNews/app/src/main/java/com/example/jetnews/utils/LazyListUtils.kt

[JetNews] Use derived state of for scrolled state to avoid recomposition on scrolling

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/EmailState.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInSignUp.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/TextFieldState.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/WelcomeScreen.kt

* Handle configuration changes for text fields
* Don't submit until data is valid
* Add keyboard type to fields
This also includes changes similar to https://github.com/android/compose-samples/pull/529, so that PR can be closed when this is merged.
cc @alexvanyo

[JetSurvey] Improve sign up process

---

JetNews/app/build.gradle

fixes #896 by changing the comment. There is another work-around we can use, but I'd rather not do work-arounds and wait for Espresso 3.5 to go stable.

[Jetnews] Be more explicit about robolectric version

---

Jetcaster/app/src/main/java/com/example/jetcaster/util/GradientScrim.kt

[Jetcaster] Fix recomposition loop in verticalGradientScrim

---

renovate.json

According to - https://docs.renovatebot.com/faq/#tell-renovate-to-ask-for-approval-before-creating-a-pull-request we can add this option to enforce manual creation of PRs from the dashboard

Disable auto creation of deps PRs for renovate

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyQuestions.kt

https://issuetracker.google.com/248164773 was fixed in material3 1.0.0-rc01, which the compose-latest branch is now on. I've removed the workaround of placing the slider in a box and confirmed it's functioning as expected on a Pixel 5.

[Jetsurvey] Removed Slider workaround for M3 bug

---

Crane/app/src/main/java/androidx/compose/samples/crane/base/BaseUserInput.kt

Fixing "Choose Destination" state restoration.

[Crane] Location input state is restored on process/activity recreation

---

Crane/gradle/libs.versions.toml
JetLagged/gradle/libs.versions.toml
JetNews/app/src/test/resources/robolectric.properties
JetNews/gradle/libs.versions.toml
Jetcaster/gradle/libs.versions.toml
Jetchat/gradle/libs.versions.toml
Jetsnack/gradle/libs.versions.toml
Jetsurvey/gradle/libs.versions.toml
Owl/gradle/libs.versions.toml
Reply/gradle/libs.versions.toml
scripts/libs.versions.toml

[All] Updated Robolectric to 4.9.1

---

Crane/app/src/main/java/androidx/compose/samples/crane/home/LandingScreen.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/Home.kt

In general, when you do
```
Box(contentAlignment = Alignment.Center) {
MyOnlyChild()
}
```
this can be simplified by:
```
MyOnlyChild(Modifier.wrapContentSize())
```
Found two occurrences of this in the samples and simplified them.

[Crane|Jetsnack] Replace box with contentAlignment for wrapContentSize modifier in child

---

JetNews/app/src/main/java/com/example/jetnews/utils/MapExtensions.kt

When I clicke any item (topic, people and publication) on Interest Screen the app crashed because of initial state (emptySet). I changed the conversion style with .toMutableSet()

[JetNews] fix jetnews empty add or remove issue on MapExtensions.kt

---

Crane/app/build.gradle.kts
Crane/benchmark/build.gradle.kts
Crane/build.gradle.kts
Crane/gradle/libs.versions.toml
JetLagged/app/build.gradle.kts
JetLagged/build.gradle.kts
JetLagged/gradle/libs.versions.toml
JetNews/app/build.gradle.kts
JetNews/build.gradle.kts
JetNews/gradle/libs.versions.toml
Jetcaster/app/build.gradle.kts
Jetcaster/build.gradle.kts
Jetcaster/gradle/libs.versions.toml
Jetchat/app/build.gradle.kts
Jetchat/build.gradle.kts
Jetchat/gradle/libs.versions.toml
Jetsnack/app/build.gradle.kts
Jetsnack/build.gradle.kts
Jetsnack/gradle/libs.versions.toml
Jetsurvey/app/build.gradle.kts
Jetsurvey/build.gradle.kts
Jetsurvey/gradle/libs.versions.toml
Owl/app/build.gradle.kts
Owl/build.gradle.kts
Owl/gradle/libs.versions.toml
Reply/app/build.gradle.kts
Reply/build.gradle.kts
Reply/gradle/libs.versions.toml
scripts/libs.versions.toml

Updates the build files to use version catalog declarations for all plugin usages.
(Small bonus: moves Jetcaster's Room usage from kapt to KSP.)

Move all plugins to version catalog

---

Jetchat/app/src/main/java/com/example/compose/jetchat/components/JetchatAppBar.kt

Fixing top bar in Jetchat's Profile screen where half of the top bar is not properly visible.
Bug introduced [here](https://github.com/android/compose-samples/compare/77fc82e64ddefaaf6481aaecfaf0e9ea9bc65199..07b0a268889ff09c2872e7efe3f7d9e1f7330e7a) with the change in `JetchatAppBar`.
before | after

[Jetchat] Fixing top bar overlap

---

Owl/app/src/main/java/com/example/owl/ui/common/CourseListItem.kt

preview without size was not useful

improved preview for CourseListItem

---

JetNews/app/src/main/java/com/example/jetnews/ui/theme/Type.kt

[JetNews] Adding Heading and Paragraph linebreak example to typography styles

---

Crane/gradle/libs.versions.toml
JetLagged/gradle/libs.versions.toml
JetNews/gradle/libs.versions.toml
Jetcaster/app/build.gradle.kts
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt
Jetcaster/app/src/main/java/com/example/jetcaster/util/GradientScrim.kt
Jetcaster/gradle/libs.versions.toml
Jetchat/gradle/libs.versions.toml
Jetsnack/gradle/libs.versions.toml
Jetsurvey/gradle/libs.versions.toml
Owl/gradle/libs.versions.toml
Reply/gradle/libs.versions.toml
scripts/libs.versions.toml

- Migrated to Foundation Pager
- Ensured pager item composable could be skipped
- Migrated gradient modifier to Modifier.Node

[Jetcaster] Improve scroll performance of podcast pager

---

Reply/app/src/main/java/com/example/reply/ui/MainActivity.kt
Reply/app/src/main/java/com/example/reply/ui/ReplyApp.kt
Reply/app/src/main/java/com/example/reply/ui/ReplyHomeViewModel.kt
Reply/app/src/main/java/com/example/reply/ui/ReplyListContent.kt
Reply/app/src/main/java/com/example/reply/ui/components/ReplyEmailListItem.kt

Allow multi-select of emails, by:
- tapping the avatar
- long-pressing the card
A selected email (during multi-select) is highlighted with a different background and a checkmark instead of the Avatar. The opened email is highlighted with a different container color.
This PR also fixes issue #1122 (ripple not clipped)

[Reply] Allow multi-select of emails and highlight the opened email

---

Reply/app/build.gradle.kts
Reply/app/src/main/java/com/example/reply/ui/ReplyListContent.kt
Reply/app/src/main/java/com/example/reply/ui/components/ReplyAppBars.kt
Reply/app/src/main/res/values/strings.xml
Reply/gradle/libs.versions.toml

Update Material 3 version to 1.1
Add new search bar component
https://github.com/android/compose-samples/assets/4903762/35c7d78a-6712-4933-89fd-e38b90b1120a

Material 1.1 release update 

---

Jetchat/README.md

Update README.md - remove Ambient

---

.github/workflows/update_deps.yml

This way, the workflow should always ask for review the person that triggered this workflow.
It also adds compose-devrel as a reviewer which might assign another person, but not sure how to remove that, since it's not defined in the action 🤔 
Tested here #1164 #1163

Use github.actor as reviewer for updating dependencies

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/RecordButton.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/UserInput.kt
Jetchat/app/src/main/res/values/strings.xml

See video.
Demonstrating:
- Cancel on horizontal swipe
- Only canceling when not too far up
- Tooltip when tapping the icon
https://github.com/android/compose-samples/assets/6952116/98c001f8-ec0f-4222-a953-528d531cb799

[Jetchat] Add recording audio button

---

Jetcaster/app/src/main/java/com/example/jetcaster/util/ViewModel.kt

Use the ViewModel factory DSL for simplicity.
https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-factories

[Jetcaster] Use the ViewModel factory DSL

---

Crane/app/src/main/java/androidx/compose/samples/crane/base/ExploreSection.kt
Crane/app/src/main/java/androidx/compose/samples/crane/home/CraneHome.kt

Fixes #1200 
Also fix lint error on home screen for an unlabelled animation

[Crane] Fix list not scrolling to bottom with ime open

---

Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInSignUp.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/WelcomeScreen.kt

Fixes #1208
I couldn't work out any reason for these Spacers to be included, please correct if wrong. @arriolac I can see you originally made this change so I am assigning you to review.
I tested small and big phones with rotation and the animated logo still works correctly when focussing on the text field.
Also some minor fixes I found during testing:
- Make the text fields single line
- Make the branding animation persist through rotation

[Jetsurvey] Remove extra spacers

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/MainActivity.kt
Jetcaster/app/src/main/res/values/themes.xml

This app already supported edge to edge layout so migrating to the new API was simple.
Phone Portrait
Tablet Landscape

[Jetcaster] Migrate Jetcaster to edge to edge API

---

Jetsurvey/app/build.gradle.kts
Jetsurvey/app/src/main/AndroidManifest.xml
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/MainActivity.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignInSignUp.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/SignUpScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/signinsignup/WelcomeScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/survey/SurveyScreen.kt
Jetsurvey/app/src/main/java/com/example/compose/jetsurvey/theme/Theme.kt
Jetsurvey/app/src/main/res/values/themes.xml

https://github.com/android/compose-samples/assets/6952116/2879eed3-4cf1-47d5-b45a-37fa51aeccd4
https://github.com/android/compose-samples/assets/6952116/a4129f06-8bd9-4a50-b839-b41f1b96597a
https://github.com/android/compose-samples/assets/6952116/758486dd-90f6-44fa-93e1-7166b77a622a

[jetsurvey] Add edge to edge support

---

Crane/app/src/main/AndroidManifest.xml
Crane/app/src/main/java/androidx/compose/samples/crane/details/DetailsActivity.kt
Crane/app/src/main/java/androidx/compose/samples/crane/home/MainActivity.kt

[Crane] Migrate to new edge to edge API

---

Jetsnack/app/build.gradle.kts
Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/Filters.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/components/Gradient.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/FilterScreen.kt
Jetsnack/app/src/main/java/com/example/jetsnack/ui/home/cart/SwipeDismissItem.kt

Replace accompanist flow layouts with compose one

---

Jetsnack/app/src/main/java/com/example/jetsnack/ui/snackdetail/SnackDetail.kt

Simply removes the superfluous code that results in an extra object being created.

Remove inefficient use of ".then" for Issue #1240

---

Jetchat/app/src/main/java/com/example/compose/jetchat/NavActivity.kt

#1256
(before) Jetchat is not laid out edge-to-edge in 2 & 3-button navigation mode (it is not drawn behind the system navigation bar in 2 & 3-button navigation mode).
(after) Jetchat is laid out edge-to-edge in 2 & 3-button navigation mode (it is drawn behind the system navigation bar in 2 & 3-button navigation mode).

Jetchat is not laid out edge-to-edge in 2 & 3-button navigation mode

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt

Center followed podcast and improve scrolling by allowing `CategoryPodcasts` to scroll along with individual episode items.
Before change:
[Screen_recording_20240226_17441dsaf1.webm](https://github.com/android/compose-samples/assets/463186/bc445db9-8337-4f17-ab30-c67e5a76c530)
With change:
[Screen_recording_20240226_173942.webm](https://github.com/android/compose-samples/assets/463186/edbfe116-b3cc-4480-aae9-5da5feacafac)

[Jetcaster] Center followed podcast and improve scrolling.

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt

Changes:
* Handles empty state when there are no subscribed podcasts (library / discover tab hidden when no podcasts are followed)
* Reverting `FollowedPodcasts` to use `HorizontalPager` so that the list of episodes changes as the user swipes through podcasts
[Screen_recording_20240321_163113.webm](https://github.com/android/compose-samples/assets/463186/0b90b672-7f04-48dd-b94a-7347e159d91e)

[Jetcaster] Handle no subscribed podcasts empty state

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/JetcasterApp.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/discover/Discover.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/library/Library.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/player/PlayerScreen.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/player/PlayerViewModel.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/theme/Theme.kt
Jetcaster/app/src/main/res/values/strings.xml
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/database/dao/EpisodesDao.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/di/Graph.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/model/PlayerEpisode.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/repository/EpisodeStore.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/player/EpisodePlayer.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/player/MockEpisodePlayer.kt
Jetcaster/core/src/test/kotlin/com/example/jetcaster/core/data/repository/TestEpisodeStore.kt

Introduces `EpisodePlayer` interface and `MockEpisodePlayer` conforming class to mock playing an episode. This enables play/pause and the slider to update as you would expect in a real podcast app. 
[Screen_recording_20240322_160937.webm](https://github.com/android/compose-samples/assets/463186/09a4e7bd-7d99-4381-8ec2-9b2af3bfefac)
#1292 should be reviewed and merged first.

[Jetcaster] Add mock support for playing an episode

---

Jetcaster/core/src/main/java/com/example/jetcaster/core/data/database/dao/PodcastsDao.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/repository/PodcastStore.kt
Jetcaster/core/src/test/kotlin/com/example/jetcaster/core/data/repository/TestPodcastStore.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/model/CategorySelection.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/JetcasterApp.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Catalog.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/search/SearchScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/search/SearchScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/theme/Space.kt
Jetcaster/tv-app/src/main/res/values/strings.xml

This pull request adds search functionality for Jetcaster. More specifically, the following changes are applied:
- Add methods implementing podcast search feature to PodcastDao and PodcastStore
- Add the search screen to the TV app

Add search functionality to Jetcaster

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/JetcasterApp.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/JetcasterAppState.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/PreviewData.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/discover/Discover.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/library/Library.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/player/PlayerViewModel.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsScreen.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsViewModel.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/shared/EpisodeListItem.kt
Jetcaster/app/src/main/res/values/strings.xml
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/database/dao/PodcastsDao.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/domain/FilterableCategoriesUseCase.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/domain/PodcastCategoryFilterUseCase.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/model/CategoryInfo.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/model/EpisodeInfo.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/model/FilterableCategoriesModel.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/model/LibraryInfo.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/model/PlayerEpisode.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/model/PodcastCategoryFilterResult.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/model/PodcastInfo.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/repository/PodcastStore.kt
Jetcaster/core/src/test/kotlin/com/example/jetcaster/core/data/domain/FilterableCategoriesUseCaseTest.kt
Jetcaster/core/src/test/kotlin/com/example/jetcaster/core/data/domain/PodcastCategoryFilterUseCaseTest.kt
Jetcaster/core/src/test/kotlin/com/example/jetcaster/core/data/repository/TestPodcastStore.kt
Jetcaster/designsystem/src/main/java/com/example/jetcaster/designsystem/theme/Keylines.kt
Jetcaster/designsystem/src/main/java/com/example/jetcaster/designsystem/theme/Shape.kt

Changes:
* Added podcast details screen. 
* Added external models `PodcastInfo`, `EpisodeInfo` and `CategoryInfo` so that composables don't depend on database entities (`Podcast`, `Episode` and `Category) directly.
Note that design is not final yet but will address that in another PR.

[Jetcaster]: Podcast screen

---

Jetcaster/app/build.gradle.kts
Jetcaster/app/src/main/java/com/example/jetcaster/ui/JetcasterApp.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/library/Library.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsScreen.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsViewModel.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/shared/EpisodeListItem.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/shared/Loading.kt
Jetcaster/gradle/libs.versions.toml

Adding `SupportingPaneScaffold` to the home screen of Jetcaster.
Remaining TODOs:
[Screen_recording_20240329_162553.webm](https://github.com/android/compose-samples/assets/463186/a5b185d3-de84-4962-a01f-d4976021dcfa)

[Jetcaster] Adding SupportingPaneScaffold to Home

---

Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/JetcasterApp.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/JetcasterAppState.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Background.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Button.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Catalog.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/ErrorState.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Thumbnail.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/discover/DiscoverScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/episode/EpisodeScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/episode/EpisodeScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/library/LibraryScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/podcast/PodcastScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/podcast/PodcastScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/search/SearchScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/theme/Space.kt
Jetcaster/tv-app/src/main/res/values/strings.xml

This pull request adds a screen to show the details of the selected episode. 
In addition to that, some improvement on focus management is also included in this pull request as follows:
- Set focusRestorer to the following components:
- PodcastRow
- EpisodeRow
- Change the tabRow in the discover screen to get the current tab selected when d-pad focus enters to the row
- Change the Library screen to get the first podcast in the PodcastRow selected when users navigate to the screen

Add a screen to show the details of the selected episode

---

Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/discover/DiscoverScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/podcast/PodcastScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/search/SearchScreen.kt

This PR fixes a build issue happening on tv-app module.  The issue was cased by the resolution failure of BasicTextField2.
More specifically the following change happen by this PR:
- Switching from BasicTextFiled2 to BasicTextField
- Modification on DiscoverScreenViewModel to remove line breaks causing a layout glitch
- Passing supportingContent parameter to ListItem instead of putting everything in the content parameter

Fix: a build error happening on TV app module

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/JetcasterApp.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/PreviewData.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/discover/Discover.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/library/Library.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsScreen.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/shared/EpisodeListItem.kt
Jetcaster/app/src/main/java/com/example/jetcaster/util/LazyVerticalGrid.kt
Jetcaster/app/src/main/java/com/example/jetcaster/util/WindowSizeClass.kt
Jetcaster/app/src/main/res/values/strings.xml

Changes:
* Showing grid of episodes in expanded width 
* Updated styles for episode item
* Updated top app bar

[Jetcaster] UI Polish

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsViewModel.kt

View model creation should happen through the factory object.

[Jetcaster]: Provide PodcastDetailsViewModel via factory.

---

Jetcaster/core/src/main/java/com/example/jetcaster/core/data/model/PlayerEpisode.kt
Jetcaster/wear/build.gradle
Jetcaster/wear/src/main/java/com/example/jetcaster/MainActivity.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/WearApp.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/home/HomeScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/library/LatestEpisodeViewModel.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/library/LatestEpisodesScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/player/PlayerScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/player/PlayerViewModel.kt

- Adds navigation to Player from latest episodes and setting the URI via EpisodePlayer
- Cleanup
- Restructured the Dialog for when the content is empty

[Jetcaster] Wear - adds navigation to player, cleanup

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsScreen.kt
Jetcaster/app/src/main/res/values/strings.xml

- Update button text in podcast details.
- Hide home category toggle when there are no subscribed podcasts.

[Jetcaster] Hide home category toggle when there are no subscribed podcasts

---

Jetcaster/core/src/main/java/com/example/jetcaster/core/data/database/dao/EpisodesDao.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/model/PlayerEpisode.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/player/EpisodePlayer.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/player/MockEpisodePlayer.kt
Jetcaster/tv-app/build.gradle.kts
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/model/EpisodeList.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/JetcasterApp.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/JetcasterAppState.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Background.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Button.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Catalog.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeCard.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeDetails.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Seekbar.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Thumbnail.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/TwoColumn.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/episode/EpisodeScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/episode/EpisodeScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/player/PlayerScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/player/PlayerScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/theme/Space.kt
Jetcaster/tv-app/src/main/res/values/strings.xml

This pull request adds the player screen to the TV app. In related to that, EpisodePlayer interface is updated so that EpisodePlayer implementations can play the given PlayerEpisode.

Add the player screen to TV app

---

Jetcaster/wear/src/main/java/com/example/jetcaster/WearApp.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/library/PodcastsScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/library/PodcastsViewModel.kt
Jetcaster/wear/src/main/res/values/strings.xml

[Wear] Adds podcasts screen

---

Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/model/EpisodeList.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/JetcasterApp.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/JetcasterAppState.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Button.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Catalog.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeRow.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/discover/DiscoverScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/discover/DiscoverScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/episode/EpisodeScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/library/LibraryScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/library/LibraryScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/player/PlayerScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/podcast/PodcastScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/podcast/PodcastScreenViewModel.kt

This pull request updates the change the screen transition when users clicks the episodes on the discovery, the library, and the podcast screen to navigate to the player screen.
This pull request also includes some code refactoring.

TV app: update action of the episode selection to navigate the player screen 

---

Jetcaster/core/src/test/kotlin/com/example/jetcaster/core/data/domain/FilterableCategoriesUseCaseTest.kt
Jetcaster/core/src/test/kotlin/com/example/jetcaster/core/data/domain/PodcastCategoryFilterUseCaseTest.kt
Jetcaster/tv-app/build.gradle.kts
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/model/EpisodeList.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/JetcasterAppState.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeCard.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeDetails.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Thumbnail.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/episode/EpisodeScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/episode/EpisodeScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/player/PlayerScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/player/PlayerScreenViewModel.kt

Fix incorrect imports. Regression introduced in #1332

[Jetcaster] Fix TV imports.

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/discover/Discover.kt
Jetcaster/app/src/main/java/com/example/jetcaster/util/GradientScrim.kt

[Jetcaster] Display radial gradient on home bg

---

Jetcaster/wear/src/main/java/com/example/jetcaster/WearApp.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/JetcasterNavController.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/library/LatestEpisodesScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/library/PodcastsScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/library/PodcastsViewModel.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsViewModel.kt
Jetcaster/wear/src/main/res/values/strings.xml

Adds a screen for the list of episodes for a Podcast

[Wear] Adds PodcastDetailsScreen

---

Jetcaster/wear/src/main/java/com/example/jetcaster/WearApp.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/components/LoadingEntityScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/components/SettingsButtons.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/home/HomeScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/library/QueueScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/library/QueueViewModel.kt
Jetcaster/wear/src/main/res/values/strings.xml

Adds the queue screen and some refactoring

[Wear] Adds queue screen

---

Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt
Jetcaster/app/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsScreen.kt
Jetcaster/designsystem/src/main/java/com/example/jetcaster/designsystem/component/PodcastImage.kt

- Added the PotcastImage component
- Added a ProgressIndicator when loading images
[image_load.webm](https://github.com/android/compose-samples/assets/38935359/7e1cfdc8-8219-4957-8e3f-a7072ac4a47d)

[Jetcaster] Add Podcast image loading

---

Jetcaster/core/src/main/java/com/example/jetcaster/core/player/EpisodePlayer.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/player/MockEpisodePlayer.kt
Jetcaster/core/src/test/kotlin/com/example/jetcaster/core/player/MockEpisodePlayerTest.kt

So that the player speed can be changed on Wear.

[Jetcaster] Add functionality to change the speed of the player

---

Jetcaster/core/model/src/main/java/com/example/jetcaster/core/model/CategoryInfo.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/database/dao/CategoriesDao.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/network/Feeds.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/data/repository/CategoryStore.kt
Jetcaster/core/src/test/kotlin/com/example/jetcaster/core/data/repository/TestCategoryStore.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt

Changes:
* Show podcasts to subscribe to in the 'Technology' category when first launching Wear app
* Fix ADB and NiA feed URLs which fixes the issue of NiA and ADB not being fetched correctly on TV and Wear

[Jetcaster]: Suggest podcasts in 'Technology' category for Wear app

---

Jetcaster/core/src/test/kotlin/com/example/jetcaster/core/data/domain/PodcastCategoryFilterUseCaseTest.kt
Jetcaster/core/src/test/kotlin/com/example/jetcaster/core/data/repository/TestCategoryStore.kt

Although this test case may become unnecessary once the `limit` parameters in each method of the `CategoryStore` are explicitly specified, I added it because it seems that there was no test code to verify the limits currently used in the `PodcastCategoryFilterUseCase`.

[Jetcaster] Add tests for podcast category filter limit

---

.github/workflows/Crane.yaml
.github/workflows/JetLagged.yaml
.github/workflows/JetNews.yaml
.github/workflows/Jetchat.yaml
.github/workflows/Owl.yaml
.github/workflows/Reply.yaml

`macOS-latest` resulted in emulators failing to run since the `macOS-latest` runner was updated to `mac14-arm64`.
Failed action with `macOS-latest`: https://github.com/android/compose-samples/actions/runs/8835086121
Confirming that this change fixes emulator runs: https://github.com/android/compose-samples/actions/runs/8837607669
...changing emulator arch to [arm64](https://github.com/android/compose-samples/blob/main/.github/workflows/Reply.yaml#L62) is perhaps another way to fix this.
Note: I had to use `macos-12` for Crane to fix emulator-related failures (see https://github.com/android/compose-samples/actions/runs/8837918596/job/24270240695)

Switch GH runners to run on ubuntu-latest

---

Jetcaster/designsystem/src/main/java/com/example/jetcaster/designsystem/component/PodcastImage.kt
Jetcaster/designsystem/src/main/java/com/example/jetcaster/designsystem/component/thumbnailPlaceholder.kt
Jetcaster/tv-app/build.gradle.kts
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/model/PodcastList.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/JetcasterApp.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Background.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Catalog.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeCard.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/PodcastCard.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/component/Thumbnail.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/discover/DiscoverScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/discover/DiscoverScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/episode/EpisodeScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/episode/EpisodeScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/library/LibraryScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/library/LibraryScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/podcast/PodcastScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/podcast/PodcastScreenViewModel.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/search/SearchScreen.kt
Jetcaster/tv-app/src/main/java/com/example/jetcaster/tv/ui/search/SearchScreenViewModel.kt

This pull request switch the component to show thumbnails in tv apps from `AsyncImage` into `PodcastImage`. As a side effect of the migration,  Podcast`, `PodcastWithExtraInfo` and `EpisodeToPodcast` are replaced with their external models.

Switching to PodcastImage

---

Reply/app/src/main/java/com/example/reply/ui/theme/Theme.kt

Currenly, Compose Previews don't support UIModeManager, so any previews using the ContrastAwareReplyTheme will fail to render when trying to apply contrast. While UIModeManager support is not added, we can work around this issue by not adding contrast in Compose Previews.

Fix Compose Previews in the Reply sample

---

Jetcaster/core/src/main/java/com/example/jetcaster/core/player/EpisodePlayer.kt
Jetcaster/core/src/main/java/com/example/jetcaster/core/player/MockEpisodePlayer.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/player/PlayerScreen.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/player/PlayerViewModel.kt

https://github.com/android/compose-samples/assets/3973717/84e7621f-d1d0-45f0-b299-e77fcf2ae335

[Jetcaster] Allow Slider seeking player

---

.github/workflows/Crane.yaml
.github/workflows/build-sample.yml
Crane/app/build.gradle.kts
JetLagged/app/build.gradle.kts
JetNews/app/build.gradle.kts
Jetcaster/mobile/build.gradle.kts
Jetchat/app/build.gradle.kts
Jetsnack/app/build.gradle.kts
Owl/app/build.gradle.kts
Reply/app/build.gradle.kts

When building from a fork pull request, the secrets are not shared. This PR removes the need to build a release since it wasn't used, named the signing config it to be a release.

Remove building release on PRs

---

Jetcaster/wear/src/main/java/com/example/jetcaster/WearApp.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/latest_episodes/LatestEpisodeViewModel.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/latest_episodes/LatestEpisodesScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/podcasts/PodcastsScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/podcasts/PodcastsViewModel.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/queue/QueueScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/queue/QueueViewModel.kt
Jetcaster/wear/src/main/res/values/strings.xml

- Inline scaffold
- Move all screens under UI package

[Wear] Use a podcast specific scaffold

---

Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/player/PlayerScreen.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsScreen.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/tooling/DevicePreviews.kt

Adds multi-device preview annotation and adjusts podcast image size in the podcast details screen so that it doesn't go over half the allotted space.

[Jetcaster]: Add DevicePreviews.

---

Jetcaster/designsystem/src/main/java/com/example/jetcaster/designsystem/component/HtmlTextContainer.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/player/PlayerScreen.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/shared/EpisodeListItem.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/shared/HtmlText.kt

[Jetcaster]: HTML format episode summary in podcast detail.

---

.github/workflows/build-sample.yml

Looks like there was a regression introduced - Jetcaster artifacts were not uplaoded on successful builds. See: https://github.com/android/compose-samples/actions/runs/8926918741
Workflow run with this change: https://github.com/android/compose-samples/actions/runs/8927043650

[GH Workflow]: Use inputs.module variable for uploading artifacts.

---

Crane/gradle/libs.versions.toml
JetLagged/gradle/libs.versions.toml
JetNews/gradle/libs.versions.toml
Jetcaster/gradle/libs.versions.toml
Jetchat/gradle/libs.versions.toml
Jetsnack/gradle/libs.versions.toml
Jetsurvey/gradle/libs.versions.toml
Owl/gradle/libs.versions.toml
Reply/gradle/libs.versions.toml
scripts/libs.versions.toml

Migrating Hilt compiler from "hilt-android-compiler" to "hilt-compiler".
"hilt-android-compiler" is renamed to "hilt-compiler"
https://github.com/google/dagger/releases/tag/dagger-2.29.1

Migrate from "hilt-android-compiler" to "hilt-compiler"

---

Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/player/PlayerScreen.kt

Change alpha of previous and next buttons in the player to help indicate if those actions are possible based on the state of the player (i.e. previous only possible while playing and next only possible when queue isn't empty).
Disabled:
Enabled:

[Jetcaster]: Change alpha of prev/next buttons.

---

Jetcaster/core/domain-testing/src/main/java/com/example/jetcaster/core/domain/testing/PreviewData.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/WearApp.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/components/MediaContent.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/episode/EpisodeScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/latest_episodes/LatestEpisodesScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/player/PlaybackSpeedScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/player/PlaybackSpeedViewModel.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/podcasts/PodcastsScreen.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/preview/WearPreviewEpisodes.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/preview/WearPreviewPodcasts.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/ui/queue/QueueScreen.kt

- Uses #1377
- Add previews for latestEpisode screen
- Refactor `MediaContent` for Queue and Podcasts (need a separate PR to see if it can be expanded for LatestEpisodes since it has additional play methods)
- Moves the latestEpisodes screen title to the Composable
- Add more data preview to create PlayerEpisode

[Wear]Add preview to latestEpisodes and refactoring

---

Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/JetcasterApp.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/JetcasterAppState.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/Catalog.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeRow.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/player/PlayerScreen.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/podcast/PodcastDetailsScreen.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/podcast/PodcastDetailsScreenViewModel.kt

This pull request fixes the following focus issues:
- The item for the current screen does not got focused when users move the d-pad focus to the NavigationDrawer
- The app crashes when users are moving d-pad focus to the podcast list from the tab item if the podcast list for the previous category is longer than current category's one
- D-pad focus moves to the different component according to the selected episode in the queue on the player screen

[Jetcaster] fix d-pad focus issues of TV app

---

Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/JetcasterApp.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeRow.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/player/PlayerScreen.kt

This PR fixes a crash bug happening on TV app: the `EpisodeRow` in the discovery screen can crash the app when users are moving d-pad focus when no visible item in the `EpisodeRow`.

[Jetcaster] Fix crash bug on TV app

---

Jetchat/app/src/main/java/com/example/compose/jetchat/conversation/UserInput.kt

Fix Issue : #1317
[succ.webm](https://github.com/android/compose-samples/assets/38935359/a022c0a6-b8fb-49aa-80b0-714fa633bf61)

Jetchat - Add KeyboardActions Support for Message Dispatch

---

Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/JetcasterApp.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/Catalog.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/component/EpisodeRow.kt
Jetcaster/tv/src/main/java/com/example/jetcaster/tv/ui/theme/Space.kt

This pull request fixes layout inconsistency in the following screens of the TV app:
- The discovery screen
- The library screen

[Jetcaster] Fix layout inconsistency in the discovery screen and the library screen

---

Reply/app/src/main/java/com/example/reply/ui/ReplyListContent.kt
Reply/app/src/main/java/com/example/reply/ui/components/ReplyAppBars.kt
Reply/app/src/main/java/com/example/reply/ui/components/ReplyEmailListItem.kt
Reply/app/src/main/java/com/example/reply/ui/components/ReplyEmailThreadItem.kt
Reply/app/src/main/java/com/example/reply/ui/navigation/ReplyNavigationActions.kt
Reply/app/src/main/java/com/example/reply/ui/navigation/ReplyNavigationComponents.kt

Replaced deprecated DockedSearchBar and removed unused codes from Reply to improve performance.

[Reply] Replaced deprecated codes and optimised performance

---

JetLagged/app/src/main/java/com/example/jetlagged/MainActivity.kt

JetLagged only supports a light theme, which means the status bar icons should always use a light theme (meaning they have to be dark). I added the statusBarStyle to the enableEdgeToEdge call to force a light theme. The bottom nav also needs to be fixed but that's more involved because every screen needs to have enough padding to push the content into view when scrolled.

Fix for status bar icon colors

---

JetNews/app/src/main/java/com/example/jetnews/ui/JetnewsApp.kt
JetNews/app/src/main/java/com/example/jetnews/ui/home/HomeScreens.kt

The floating toolbar seen in expanded width windows was implemented as a sticky header. The problem with that is it allows the toolbar to go behind the status bar on scroll due to edge-to-edge. For a real sticky header, you'd probably want to implement inset handling into the header so that it sticks just below any insets. In this case, that would mean the toolbar never actually moves, so I pulled it out of sticky header and just put it as a sibling with the LazyColumn. By adding the safeDrawing insets, this keeps it positioned at the top right of the safeDrawing area.
I also added a BackHandler for the drawer, so that pressing back closes the drawer. I don't see any clean way to implement predictive back with a modal navigation drawer.

Fixed spacing for floating toolbar + back support

---

JetLagged/app/src/main/java/com/example/jetlagged/JetLaggedScreen.kt

Since the headder and the body (FlowRow) are sibling elements, we have to explicitly exclude the top inset, which we get by combining the bottom and the sides (horizontal). Tested with all the developer options notch settings and with both gesture nav and 3 button nav.
I did not override the navigationBarStyle since the default actually seems to work well. With three button nav, it has a partially transparent light background that helps the buttons stand out when content is behind them. With gesture nav, the bar stands out enough on its own.
This fixes #1450.

Added window insets to the the main screen

---

Jetchat/app/src/main/AndroidManifest.xml
Jetchat/app/src/main/java/com/example/compose/jetchat/NavActivity.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/components/JetchatDrawer.kt
Jetchat/app/src/main/java/com/example/compose/jetchat/components/JetchatScaffold.kt
Jetchat/gradle/libs.versions.toml

In M3 1.3, the drawerState can be passed to the ModalDrawerSheet to get predictive back animations without the need for a PredictiveBackHandler to be manually defined. I also moved the color settings to the correct place (ModalDrawerSheet) to make sure the drawer portions covered by insets would be colored correctly.

Added predictive back support to Jetchat drawer

---

Jetcaster/core/designsystem/src/main/java/com/example/jetcaster/designsystem/component/HtmlTextContainer.kt

HTML formatting support from compose 1.7.0

[Jetcaster] Refactor to use fromHtml in AnnotatedString

---

Jetcaster/core/data/src/main/java/com/example/jetcaster/core/data/network/PodcastFetcher.kt

Fixes part of #1461 
JetCaster showed a blank screen when run. The podcast fetching was running on the main dispatcher. Moved the withContext() up to ensure all IO was being performed on the IO dispatcher.

Moved withContext() call up to surround all IO being performed. 

---

JetLagged/gradle/libs.versions.toml
JetNews/gradle/libs.versions.toml
Jetcaster/gradle/libs.versions.toml
Jetchat/gradle/libs.versions.toml
Jetsnack/gradle/libs.versions.toml
Reply/gradle/libs.versions.toml
scripts/libs.versions.toml
scripts/updateDeps.sh

Fixed #1478 by using the correct version variable for `kotlinx-coroutines-test`
Also changed the master project used for version updates from `JetNews` to `Reply`. 
Why? `JetNews` doesn't use the `kotlinx-serialization` plugin so this was automatically removed when running `versionCatalogUpdate` gradle task. This meant that `Reply` would fail to build because it depends on this plugin.

Fix dependency updates

---

Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/Home.kt

AppBar was missing a start padding that caused it to extend to the edge of the screen on Compact size classes.
Updated the SearchBar component usage away from the deprecated method version as an internal usage of Modifier.fillMaxWidth in the deprecated method was now causing the AppBar to always fill max width on all Window Size Classes (vs the intended end-aligned smaller version in non-Compact)
Phone - after
Phone - before
Tablet - after
Tablet - before

Fix AppBar padding and alignment issues

---

Jetcaster/glancewidget/build.gradle.kts
Jetcaster/mobile/build.gradle.kts

reference to #1487
Afflicted modules have been updated with the new gradle typesafe import API

[Jetcaster] Update gradle typesafe import

---

Jetcaster/core/designsystem/src/main/java/com/example/jetcaster/designsystem/component/PodcastImage.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/JetcasterApp.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/category/PodcastCategory.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/discover/Discover.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/library/Library.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/player/PlayerScreen.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/util/SafeSharedElement.kt

[Jetcaster] Fixed to enable SharedElementTransition to run in the Grid list

---

Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/Home.kt

Fixes #1508 by only calling `HomeScreen` in a single source code location, in the main pane of `SupportingPaneScaffold`.

[Jetcaster] Use one HomeScreen call inside SupportingPaneScaffold

---

Jetcaster/core/data/src/main/java/com/example/jetcaster/core/data/repository/PodcastsRepository.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt

[Merge after #1498]
- This PR merges the home UI state into one data class to be able to show loading state and content state at the same time.
- It also fixes the progress to wait for the loading to finish.
- Instead of circular progress, I switched to linear progress at the top of the content, which can indicate the work while showing content
**After**
https://github.com/user-attachments/assets/ec3e9220-addc-4b96-9b6a-477294b6cf85
**Before**
https://github.com/user-attachments/assets/c795afc3-01f6-407b-b0b6-505da33652ec

[Jetcaster] Refactor home state and fix loading progress

---

Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt

[Merge after #1499]
- it served only as a wrapper for parameters without any additional logic
- it was unstable and creating new instance each composition, therefore no skipping
- Reduces amount of passing and potentially making mistake

[Jetcaster] Remove HomeState and reduces lambdas into HomeAction

---

Jetcaster/README.md

PR adjusts the references in `Jetcaster/README.md`. It also fixes small typo (_`Advice` cannot be pluralized by adding the suffix -s_).

[Jetcaster]: Update references in README

---

Jetcaster/mobile/src/main/AndroidManifest.xml
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/JetcasterApp.kt

Add predictive back animations (back-to-home) and in-app animations to JetCaster
https://github.com/user-attachments/assets/3649450c-46a5-4c43-82f6-63ba9d4b4bbe

[JetCaster] enable predictive back animations and add in pb NavHost animations

---

Jetcaster/wear/src/main/java/com/example/jetcaster/MainActivity.kt
Jetcaster/wear/src/main/java/com/example/jetcaster/WearApp.kt
Jetcaster/wear/src/test/java/com/example/jetcaster/NavigationTest.kt

Also add a unit test covering activity startup and navigation

Fix Wear navigation startDestination

---

Reply/app/src/main/AndroidManifest.xml

Enable predictive back in the Reply sample

[Reply] Enable predictive back 

---

Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/JetcasterAppState.kt

This code is not being used and looks to be a duplicate of ARG_PODCAST_URI in the companion object. This could lead to unexpected issues in the future.
Noticed while reading thru the code and just wanted to contribute back 😁

Remove unused code

---

.github/CODEOWNERS

There's currently two different CODEOWNERS. We're keeping only one

Keep one CODEOWNERS

---

Jetcaster/core/data/src/main/java/com/example/jetcaster/core/data/database/model/EpisodeToPodcast.kt
Jetcaster/core/domain/src/main/java/com/example/jetcaster/core/model/CategoryInfo.kt
Jetcaster/core/domain/src/main/java/com/example/jetcaster/core/model/EpisodeInfo.kt
Jetcaster/core/domain/src/main/java/com/example/jetcaster/core/model/FilterableCategoriesModel.kt
Jetcaster/core/domain/src/main/java/com/example/jetcaster/core/model/PodcastCategoryFilterResult.kt
Jetcaster/core/domain/src/main/java/com/example/jetcaster/core/model/PodcastInfo.kt
Jetcaster/core/domain/src/main/java/com/example/jetcaster/core/model/PodcastToEpisodeInfo.kt
Jetcaster/core/domain/src/main/java/com/example/jetcaster/core/player/EpisodePlayer.kt
Jetcaster/core/domain/src/main/java/com/example/jetcaster/core/player/model/PlayerEpisode.kt
Jetcaster/mobile/build.gradle.kts
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/Home.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/home/HomeViewModel.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsScreen.kt
Jetcaster/mobile/src/main/java/com/example/jetcaster/ui/podcast/PodcastDetailsViewModel.kt
Jetcaster/stability_config.conf
Jetcaster/tv/build.gradle.kts
Jetcaster/wear/build.gradle

Add stability configuration and apply @Immutable annotation to data classes, add fix type method
**After add stability configuration**

Add stability configuration and apply @Immutable annotation to data classes
